openapi: 3.0.3

info:
  title: Cosmo Tech ScenarioRun Manager API
  description: Cosmo Tech ScenarioRun Manager API
  version: 0.0.8-SNAPSHOT

servers:
- url: 'https://api.azure.cosmo-platform.com'
- url: 'http://localhost:4010'

security:
- oAuth2AuthCode: [ ]

tags:
- name: scenariorun
  description: ScenarioRun Management

paths:
  /organizations/{organization_id}/scenarioruns/search:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
    post:
      operationId: searchScenarioRuns
      tags:
        - scenariorun
      summary: Search ScenarioRuns
      requestBody:
        description: the ScenarioRun search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScenarioRunSearch'
            examples:
              BrewerySearch:
                $ref: '#/components/examples/BrewerySearch'
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              BrewerySearch:
                $ref: '#/components/examples/BrewerySearch'
      responses:
        "200":
          description: the scenariorun details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScenarioRun'
              examples:
                OneScenarioRun:
                  $ref: '#/components/examples/OneScenarioRun'
  /organizations/{organization_id}/scenarioruns/startcontainers:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
    post:
      operationId: startScenarioRunContainers
      tags:
        - scenariorun
      summary: Start a new scenariorun with raw containers definition
      requestBody:
        description: the raw containers definition
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScenarioRunStartContainers'
            examples:
              ScenarioRunStartContainers:
                $ref: '#/components/examples/BreweryScenarioRunStartContainers'
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              ScenarioRunStartContainers:
                $ref: '#/components/examples/BreweryScenarioRunStartContainers'
      responses:
        "202":
          description: the scenariorun details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScenarioRun'
              examples:
                ScenarioRun:
                  $ref: '#/components/examples/BreweryScenarioRunContainer'
        "400":
          description: Bad request
        "404":
          description: the Scenario specified is unknown or you don't have access to it
  /organizations/{organization_id}/scenarioruns/{scenariorun_id}:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: scenariorun_id
        in: path
        description: the ScenarioRun identifier
        required: true
        schema:
          type: string
    get:
      operationId: findScenarioRunById
      tags:
        - scenariorun
      summary: Get the details of a scenariorun
      responses:
        "200":
          description: the ScenarioRun details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScenarioRun'
              examples:
                ScenarioRun:
                  $ref: '#/components/examples/BreweryScenarioRun'
        "404":
          description: the ScenarioRun specified is unknown or you don't have access to it
    delete:
      operationId: deleteScenarioRun
      tags:
        - scenariorun
      summary: Delete a scenariorun
      responses:
        "204":
          description: Request succeeded
        "400":
          description: Bad request
        "404":
          description: the ScenarioRun specified is unknown or you don't have access to it
  /organizations/{organization_id}/scenarioruns/{scenariorun_id}/status:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: scenariorun_id
        in: path
        description: the ScenarioRun identifier
        required: true
        schema:
          type: string
    get:
      operationId: getScenarioRunStatus
      tags:
        - scenariorun
      summary: get the status for the ScenarioRun
      responses:
        "200":
          description: the scenariorun status details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScenarioRunStatus'
              examples:
                ScenarioRun:
                  $ref: '#/components/examples/BreweryScenarioRunStatus'
  /organizations/{organization_id}/scenarioruns/{scenariorun_id}/logs:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: scenariorun_id
        in: path
        description: the ScenarioRun identifier
        required: true
        schema:
          type: string
    get:
      operationId: getScenarioRunLogs
      tags:
        - scenariorun
      summary: get the logs for the ScenarioRun
      responses:
        "200":
          description: the scenariorun logs details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScenarioRunLogs'
              examples:
                ScenarioRun:
                  $ref: '#/components/examples/BreweryScenarioRunLogs'
  /organizations/{organization_id}/scenarioruns/{scenariorun_id}/cumulatedlogs:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: scenariorun_id
        in: path
        description: the ScenarioRun identifier
        required: true
        schema:
          type: string
    get:
      operationId: getScenarioRunCumulatedLogs
      tags:
        - scenariorun
      summary: Get the cumulated logs of a scenariorun
      responses:
        "200":
          description: the ScenarioRun cumulated logs
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: Bad request
        "404":
          description: the ScenarioRun specified is unknown or you don't have access to it
  /organizations/{organization_id}/workspaces/{workspace_id}/scenarioruns:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
    get:
      operationId: getWorkspaceScenarioRuns
      tags:
        - scenariorun
      summary: get the list of ScenarioRuns for the Workspace
      responses:
        "200":
          description: the scenariorun details list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScenarioRun'
              examples:
                OneScenarioRun:
                  $ref: '#/components/examples/OneScenarioRun'
  /organizations/{organization_id}/workspaces/{workspace_id}/scenarios/{scenario_id}/scenarioruns:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
      - name: scenario_id
        in: path
        description: the Scenario identifier
        required: true
        schema:
          type: string
    get:
      operationId: getScenarioRuns
      tags:
        - scenariorun
      summary: get the list of ScenarioRuns for the Scenario
      responses:
        "200":
          description: the scenariorun details list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScenarioRun'
              examples:
                OneScenarioRun:
                  $ref: '#/components/examples/OneScenarioRun'
  /organizations/{organization_id}/workspaces/{workspace_id}/scenarios/{scenario_id}/run:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
      - name: scenario_id
        in: path
        description: the Scenario identifier
        required: true
        schema:
          type: string
    post:
      operationId: runScenario
      tags:
        - scenariorun
      summary: run a ScenarioRun for the Scenario
      responses:
        "200":
          description: the scenariorun details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScenarioRun'
              examples:
                ScenarioRun:
                  $ref: '#/components/examples/BreweryScenarioRun'
components:
  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: OAuth2 authentication
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          scopes:
            http://dev.api.cosmotech.com/platform: Platform scope
  schemas:
    ScenarioRunSearch:
      type: object
      description: the search options
      properties:
        solutionId:
          type: string
          description: the Solution Id to search
        runTemplateId:
          type: string
          description: the Solution Analysis Id to search
        workspaceId:
          type: string
          description: the Workspace Id to search
        scenarioId:
          type: string
          description: the Scenario Id to search
        state:
          type: string
          description: the state to search
          enum: ["FetchingDatasets","FetchingScenarioParameters","ApplyingScenarioParameters","ValidatingScenarioData","SendingScenarioDataToDataWarehouse","PreRun","Running","PostRun","Success","Failed"]
        workflowId:
          type: string
          description: the Cosmo Tech compute cluster Argo Workflow Id to search
        workflowName:
          type: string
          description: the Cosmo Tech compute cluster Argo Workflow Name
        ownerId:
          type: string
          description: the owner Id to search
    ScenarioRunStartContainers:
      type: object
      description: the parameters to run directly containers
      properties:
        generateName:
          type: string
          description: the base name for workflow name generation
        csmSimulationId:
          type: string
          description: Cosmo Tech Simulation Run Id
        nodeLabel:
          type: string
          description: the node label request
        labels:
          type: object
          description: the workflow labels
          additionalProperties:
            type: string
        containers:
          type: array
          description: the containerslist
          items:
            $ref: '#/components/schemas/ScenarioRunContainer'
      required:
        - csmSimulationId
        - containers
    ScenarioRunStatus:
      type: object
      description: a ScenarioRun status
      properties:
        id:
          type: string
          description: the ScenarioRun id
        organizationId:
          type: string
          description: the ScenarioRun id
        workflowId:
          type: string
          description: the Cosmo Tech compute cluster Argo Workflow Id to search
        workflowName:
          type: string
          description: the Cosmo Tech compute cluster Argo Workflow Name
        startTime:
          type: string
          description: the ScenarioRun start Date Time
        endTime:
          type: string
          description: the ScenarioRun end Date Time
        phase:
          type: string
          description: high-level summary of where the workflow is in its lifecycle
        progress:
          type: string
          description: progress to completion
        message:
          type: string
          description: a  human readable message indicating details about why the workflow is in this condition
        estimatedDuration:
          type: integer
          description: estimatedDuration in seconds
        nodes:
          type: array
          description: status of ScenarioRun nodes
          items:
            $ref: '#/components/schemas/ScenarioRunStatusNode'
        state:
          type: string
          enum:
            - Running
            - Successful
            - Failed
            - Unknown
            # PROD-7420 : return data ingestion status
            - DataIngestionInProgress
            - DataIngestionFailure
    ScenarioRunStatusNode:
      type: object
      description: status of a ScenarioRun Node
      properties:
        id:
          type: string
          description: the node id
        name:
          type: string
          description: the node unique name
        containerName:
          type: string
          description: the ScenarioRun container name
        estimatedDuration:
          type: integer
          description: estimatedDuration in seconds
        hostNodeName:
          type: string
          description: HostNodeName name of the Kubernetes node on which the Pod is running, if applicable
        message:
          type: string
          description: a human readable message indicating details about why the node is in this condition
        phase:
          type: string
          description: high-level summary of where the node is in its lifecycle
        progress:
          type: string
          description: progress to completion
        startTime:
          type: string
          description: the node start time
        endTime:
          type: string
          description: the node end time
    ScenarioRun:
      type: object
      description: a ScenarioRun with only base properties
      properties:
        id:
          type: string
          readOnly: true
          description: the ScenarioRun
        organizationId:
          type: string
          description: the Organization id
        workflowId:
          type: string
          description: the Cosmo Tech compute cluster Argo Workflow Id to search
        csmSimulationRun:
          type: string
          readOnly: true
          description: the Cosmo Tech Simulation Run Id
        generateName:
          type: string
          description: the base name for workflow name generation
        workflowName:
          type: string
          description: the Cosmo Tech compute cluster Argo Workflow Name
        ownerId:
          type: string
          readOnly: true
          description: the user id which own this scenariorun
        workspaceId:
          type: string
          readOnly: true
          description: the Workspace Id
        workspaceKey:
          type: string
          readOnly: true
          description: technical key for resource name convention and version grouping. Must be unique
        scenarioId:
          type: string
          readOnly: true
          description: the Scenario Id
        solutionId:
          type: string
          readOnly: true
          description: the Solution Id
        runTemplateId:
          type: string
          readOnly: true
          description: the Solution Run Template id
        computeSize:
          type: string
          readOnly: true
          description: the compute size needed for this Analysis. Standard sizes are basic and highcpu. Default is basic
        datasetList:
          type: array
          readOnly: true
          description: the list of Dataset Id associated to this Analysis
          items:
            type: string
        parametersValues:
          type: array
          readOnly: true
          description: the list of Run Template parameters values
          items:
            $ref: '#/components/schemas/RunTemplateParameterValue'
        sendDatasetsToDataWarehouse:
          type: boolean
          readOnly: true
          description: whether or not the Datasets values are send to the DataWarehouse prior to Simulation Run. If not set follow the Workspace setting
        sendInputParametersToDataWarehouse:
          type: boolean
          readOnly: true
          description: whether or not the input parameters values are send to the DataWarehouse prior to Simulation Run. If not set follow the Workspace setting
        nodeLabel:
          type: string
          readOnly: true
          description: the node label request
        containers:
          type: array
          description: the containers list
          items:
            $ref: '#/components/schemas/ScenarioRunContainer'
    RunTemplateParameterValue:
      type: object
      description: the value of Analysis parameter for a Scenario for this ScenarioRun
      properties:
        parameterId:
          type: string
          description: the parameter Id
        varType:
          type: string
          readOnly: true
          description: the parameter value type
        value:
          type: string
          description: the parameter value
      required:
        - parameterId
        - value
    ScenarioRunContainer:
      type: object
      description: a ScenarioRun container description
      properties:
        id:
          type: string
          readOnly: true
          description: the container Id
        name:
          type: string
          description: the container name
        labels:
          type: object
          description: the metadata labels
          additionalProperties:
            type: string
        envVars:
          type: object
          description: environment variable map
          additionalProperties:
            type: string
        image:
          type: string
          description: the container image URI
        entrypoint:
          type: string
          description: the container entry point
        runArgs:
          type: array
          description: the list of run arguments for the container
          items:
            type: string
        dependencies:
          type: array
          description: the list of dependencies container name to run this container
          items:
            type: string
        solutionContainer:
          type: boolean
          readOnly: true
          description: whether or not this container is a Cosmo Tech solution container
        artifacts:
          type: array
          description: the list of artifacts
          items:
            $ref: '#/components/schemas/ScenarioRunContainerArtifact'
      required:
        - name
        - image
    ScenarioRunContainerArtifact:
      type: object
      description: a scenario run container artifact
      properties:
        name:
          type: string
          description: the artifact name
        path:
          type: string
          description: the artifact path (relative to /var/csmoutput)
    ScenarioRunLogs:
      type: object
      description: the scenariorun logs returned by all containers
      properties:
        scenariorunId:
          type: string
          readOnly: true
          description: the ScenarioRun Id
        containers:
          type: object
          readOnly: true
          description: the container map of logs
          additionalProperties:
            $ref: '#/components/schemas/ScenarioRunContainerLogs'
    ScenarioRunContainerLogs:
      type: object
      description: logs for a given container
      properties:
        nodeId:
          type: string
          readOnly: true
          description: the node Id which has executed this log
        containerName:
          type: string
          readOnly: true
          description: the container name
        children:
          type: array
          readOnly: true
          description: the list of children node id
          items:
            type: string
        logs:
          type: string
          readOnly: true
          description: the node logs in plain text
  examples:
    BreweryScenarioRun:
      summary: Brewery ScenarioRun example
      description: Brewery ScenarioRun example
      value:
        id: SR-bDMr5lM9Vp
        organizationId: O-x2QOMVXpjX
        workflowId: 07193ced-9895-444f-b2be-31e8bfc3e768
        csmSimulationRun: a2880d46-a60d-4215-a593-783452e0df8f
        generateName: workflow-s-eeypwem0kw-
        workflowName: workflow-s-eeypwem0kw-lsczk
        ownerId: null
        workspaceId: W-OGNQqJ7wP0
        workspaceKey: Brewery
        scenarioId: S-EEYpWeM0kW
        solutionId: SOL-w4Kn79JXKz
        runTemplateId: hundred
        computeSize: '%NONE%'
        datasetList: null
        parametersValues: null
        sendDatasetsToDataWarehouse: false
        sendInputParametersToDataWarehouse: false
        nodeLabel: null
        containers:
          - name: applyParametersContainer
            image: localhost:5000/vcrbrewery_simulator:0.0.5
            id: null
            envVars:
              AZURE_TENANT_ID: e9641c78-d0d6-4d09-af63-168922724e7f
              AZURE_CLIENT_ID: 1d742f67-369a-444f-b0f3-ab37a9190c48
              AZURE_CLIENT_SECRET: e_jXgwQicuE4l4Dyo4v.2_3aZxM5PL9V.P
              CSM_API_URL: https://api.comostech.com///latest
              CSM_DATASET_ABSOLUTE_PATH: /mnt/scenariorun-data
              CSM_PARAMETERS_ABSOLUTE_PATH: /mnt/scenariorun-parameters
              CSM_RUN_TEMPLATE_ID: hundred
              CSM_CONTAINER_MODE: handle-parameters
              CSM_CONTROL_PLANE_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery-scenariorun
              CSM_PROBES_MEASURES_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery
              CSM_SIMULATION: DeployedSimulation
            entrypoint: entrypoint.py
            runArgs: null
            dependencies: null
          - name: validateDataContainer
            image: localhost:5000/vcrbrewery_simulator:0.0.5
            id: null
            envVars:
              AZURE_TENANT_ID: e9641c78-d0d6-4d09-af63-168922724e7f
              AZURE_CLIENT_ID: 1d742f67-369a-444f-b0f3-ab37a9190c48
              AZURE_CLIENT_SECRET: e_jXgwQicuE4l4Dyo4v.2_3aZxM5PL9V.P
              CSM_API_URL: https://api.comostech.com///latest
              CSM_DATASET_ABSOLUTE_PATH: /mnt/scenariorun-data
              CSM_PARAMETERS_ABSOLUTE_PATH: /mnt/scenariorun-parameters
              CSM_RUN_TEMPLATE_ID: hundred
              CSM_CONTAINER_MODE: validate
              CSM_CONTROL_PLANE_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery-scenariorun
              CSM_PROBES_MEASURES_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery
              CSM_SIMULATION: DeployedSimulation
            entrypoint: entrypoint.py
            runArgs: null
            dependencies: null
          - name: preRunContainer
            image: localhost:5000/vcrbrewery_simulator:0.0.5
            id: null
            envVars:
              AZURE_TENANT_ID: e9641c78-d0d6-4d09-af63-168922724e7f
              AZURE_CLIENT_ID: 1d742f67-369a-444f-b0f3-ab37a9190c48
              AZURE_CLIENT_SECRET: e_jXgwQicuE4l4Dyo4v.2_3aZxM5PL9V.P
              CSM_API_URL: https://api.comostech.com///latest
              CSM_DATASET_ABSOLUTE_PATH: /mnt/scenariorun-data
              CSM_PARAMETERS_ABSOLUTE_PATH: /mnt/scenariorun-parameters
              CSM_RUN_TEMPLATE_ID: hundred
              CSM_CONTAINER_MODE: prerun
              CSM_CONTROL_PLANE_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery-scenariorun
              CSM_PROBES_MEASURES_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery
              CSM_SIMULATION: DeployedSimulation
            entrypoint: entrypoint.py
            runArgs: null
            dependencies: null
          - name: runContainer
            image: localhost:5000/vcrbrewery_simulator:0.0.5
            id: null
            envVars:
              AZURE_TENANT_ID: e9641c78-d0d6-4d09-af63-168922724e7f
              AZURE_CLIENT_ID: 1d742f67-369a-444f-b0f3-ab37a9190c48
              AZURE_CLIENT_SECRET: e_jXgwQicuE4l4Dyo4v.2_3aZxM5PL9V.P
              CSM_API_URL: https://api.comostech.com///latest
              CSM_DATASET_ABSOLUTE_PATH: /mnt/scenariorun-data
              CSM_PARAMETERS_ABSOLUTE_PATH: /mnt/scenariorun-parameters
              CSM_RUN_TEMPLATE_ID: hundred
              CSM_CONTAINER_MODE: engine
              CSM_CONTROL_PLANE_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery-scenariorun
              CSM_PROBES_MEASURES_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery
              CSM_SIMULATION: DeployedSimulation
            entrypoint: entrypoint.py
            runArgs: null
            dependencies: null
          - name: postRunContainer
            image: localhost:5000/vcrbrewery_simulator:0.0.5
            id: null
            envVars:
              AZURE_TENANT_ID: e9641c78-d0d6-4d09-af63-168922724e7f
              AZURE_CLIENT_ID: 1d742f67-369a-444f-b0f3-ab37a9190c48
              AZURE_CLIENT_SECRET: e_jXgwQicuE4l4Dyo4v.2_3aZxM5PL9V.P
              CSM_API_URL: https://api.comostech.com///latest
              CSM_DATASET_ABSOLUTE_PATH: /mnt/scenariorun-data
              CSM_PARAMETERS_ABSOLUTE_PATH: /mnt/scenariorun-parameters
              CSM_RUN_TEMPLATE_ID: hundred
              CSM_CONTAINER_MODE: postrun
              CSM_CONTROL_PLANE_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery-scenariorun
              CSM_PROBES_MEASURES_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery
              CSM_SIMULATION: DeployedSimulation
            entrypoint: entrypoint.py
            runArgs: null
            dependencies: null
    BreweryScenarioRunContainer:
      summary: Brewery ScenarioRun Containers example
      description: Brewery ScenarioRun ran with containers information example
      value:
        id: "1"
        workflowId: "1"
        workflowName: "w1"
        ownerId: "1"
        state: Running
        startTime: 4/15/2021, 10:52:18.593 AM
        nodeLabel: highcpupool
        fetchDatasetContainers:
          - id: azertyuiop
            envVars:
              AZURE_TENANT_ID: "12345678"
              AZURE_CLIENT_ID: "12345678"
              AZURE_CLIENT_SECRET: azertyuiop
              CSM_API_URL: https://api.comostech.com
              CSM_API_TOKEN: azertyuiopqsdfghjklm
              ADT_INSTANCE_URL: https://supply.api.weu.digitaltwins.azure.net
              ADT_QUERY: SELECT * FROM digitaltwins
              CSM_DATASET_ABSOLUTE_PATH: /mnt/scenariorun-data
            image: csmphoenix.azurecr.io/azure-digital-twins-simulator-connector:latest
        sendDataWarehouseContainer:
          id: qsdfghjklm
          envVars:
            AZURE_TENANT_ID: "12345678"
            AZURE_CLIENT_ID: "12345678"
            AZURE_CLIENT_SECRET: azertyuiop
            CSM_API_URL: https://api.comostech.com
            CSM_API_TOKEN: azertyuiopqsdfghjklm
            CSM_DATASET_ABSOLUTE_PATH: /mnt/scenariorun-data
            CSM_PARAMETERS_ABSOLUTE_PATH: /mnt/scenariorun-parameters
            CSM_SEND_DATAWAREHOUSE_PARAMETERS: true
            CSM_SEND_DATAWAREHOUSE_DATASETS: true
            ADX_DATA_INGESTION_URI: https://ingest-phoenix.westeurope.kusto.windows.net
            ADX_DATABASE: Brewery
          image: csmphoenix.azurecr.io/azure-data-explorer-scenariorun-sender:latest
        runContainer:
          id: wxcvbn
          envVars:
            AZURE_TENANT_ID: "12345678"
            AZURE_CLIENT_ID: "12345678"
            AZURE_CLIENT_SECRET: azertyuiop
            CSM_API_URL: https://api.comostech.com
            CSM_API_TOKEN: azertyuiopqsdfghjklm
            CSM_ENGINE_PROVIDER: local
            CSM_ENGINE_PATH: run_templates/hundred/engine/
            CSM_DATASET_ABSOLUTE_PATH: /mnt/scenariorun-data
            CSM_PARAMETERS_ABSOLUTE_PATH: /mnt/scenariorun-parameters
            CSM_CONTROL_PLANE_TOPIC: amqps://csm-phoenix.servicebus.windows.net/organizationid-brewery-scenariorun
            CSM_PROBES_MEASURES_TOPIC: amqps://csm-phoenix.servicebus.windows.net/organizationid-brewery
            CSM_CONTAINER_MODE: engine
            CSM_SIMULATION: DeployedScenarioRun
          image: twinengines.azurecr.io/brewery_simulator:latest
          entrypoint: entrypoint.py
    OneScenarioRun:
      summary: Brewery ScenarioRun list example
      description: Brewery ScenarioRun list example
      value:
        - id: SR-bDMr5lM9Vp
          organizationId: O-x2QOMVXpjX
          workflowId: 07193ced-9895-444f-b2be-31e8bfc3e768
          csmSimulationRun: a2880d46-a60d-4215-a593-783452e0df8f
          generateName: workflow-s-eeypwem0kw-
          workflowName: workflow-s-eeypwem0kw-lsczk
          ownerId: null
          workspaceId: W-OGNQqJ7wP0
          workspaceKey: Brewery
          scenarioId: S-EEYpWeM0kW
          solutionId: SOL-w4Kn79JXKz
          runTemplateId: hundred
          computeSize: '%NONE%'
          datasetList: null
          parametersValues: null
          sendDatasetsToDataWarehouse: false
          sendInputParametersToDataWarehouse: false
          nodeLabel: null
          containers:
            - name: applyParametersContainer
              image: localhost:5000/vcrbrewery_simulator:0.0.5
              id: null
              envVars:
                AZURE_TENANT_ID: e9641c78-d0d6-4d09-af63-168922724e7f
                AZURE_CLIENT_ID: 1d742f67-369a-444f-b0f3-ab37a9190c48
                AZURE_CLIENT_SECRET: e_jXgwQicuE4l4Dyo4v.2_3aZxM5PL9V.P
                CSM_API_URL: https://api.comostech.com///latest
                CSM_DATASET_ABSOLUTE_PATH: /mnt/scenariorun-data
                CSM_PARAMETERS_ABSOLUTE_PATH: /mnt/scenariorun-parameters
                CSM_RUN_TEMPLATE_ID: hundred
                CSM_CONTAINER_MODE: handle-parameters
                CSM_CONTROL_PLANE_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery-scenariorun
                CSM_PROBES_MEASURES_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery
                CSM_SIMULATION: DeployedSimulation
              entrypoint: entrypoint.py
              runArgs: null
              dependencies: null
            - name: validateDataContainer
              image: localhost:5000/vcrbrewery_simulator:0.0.5
              id: null
              envVars:
                AZURE_TENANT_ID: e9641c78-d0d6-4d09-af63-168922724e7f
                AZURE_CLIENT_ID: 1d742f67-369a-444f-b0f3-ab37a9190c48
                AZURE_CLIENT_SECRET: e_jXgwQicuE4l4Dyo4v.2_3aZxM5PL9V.P
                CSM_API_URL: https://api.comostech.com///latest
                CSM_DATASET_ABSOLUTE_PATH: /mnt/scenariorun-data
                CSM_PARAMETERS_ABSOLUTE_PATH: /mnt/scenariorun-parameters
                CSM_RUN_TEMPLATE_ID: hundred
                CSM_CONTAINER_MODE: validate
                CSM_CONTROL_PLANE_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery-scenariorun
                CSM_PROBES_MEASURES_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery
                CSM_SIMULATION: DeployedSimulation
              entrypoint: entrypoint.py
              runArgs: null
              dependencies: null
            - name: preRunContainer
              image: localhost:5000/vcrbrewery_simulator:0.0.5
              id: null
              envVars:
                AZURE_TENANT_ID: e9641c78-d0d6-4d09-af63-168922724e7f
                AZURE_CLIENT_ID: 1d742f67-369a-444f-b0f3-ab37a9190c48
                AZURE_CLIENT_SECRET: e_jXgwQicuE4l4Dyo4v.2_3aZxM5PL9V.P
                CSM_API_URL: https://api.comostech.com///latest
                CSM_DATASET_ABSOLUTE_PATH: /mnt/scenariorun-data
                CSM_PARAMETERS_ABSOLUTE_PATH: /mnt/scenariorun-parameters
                CSM_RUN_TEMPLATE_ID: hundred
                CSM_CONTAINER_MODE: prerun
                CSM_CONTROL_PLANE_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery-scenariorun
                CSM_PROBES_MEASURES_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery
                CSM_SIMULATION: DeployedSimulation
              entrypoint: entrypoint.py
              runArgs: null
              dependencies: null
            - name: runContainer
              image: localhost:5000/vcrbrewery_simulator:0.0.5
              id: null
              envVars:
                AZURE_TENANT_ID: e9641c78-d0d6-4d09-af63-168922724e7f
                AZURE_CLIENT_ID: 1d742f67-369a-444f-b0f3-ab37a9190c48
                AZURE_CLIENT_SECRET: e_jXgwQicuE4l4Dyo4v.2_3aZxM5PL9V.P
                CSM_API_URL: https://api.comostech.com///latest
                CSM_DATASET_ABSOLUTE_PATH: /mnt/scenariorun-data
                CSM_PARAMETERS_ABSOLUTE_PATH: /mnt/scenariorun-parameters
                CSM_RUN_TEMPLATE_ID: hundred
                CSM_CONTAINER_MODE: engine
                CSM_CONTROL_PLANE_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery-scenariorun
                CSM_PROBES_MEASURES_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery
                CSM_SIMULATION: DeployedSimulation
              entrypoint: entrypoint.py
              runArgs: null
              dependencies: null
            - name: postRunContainer
              image: localhost:5000/vcrbrewery_simulator:0.0.5
              id: null
              envVars:
                AZURE_TENANT_ID: e9641c78-d0d6-4d09-af63-168922724e7f
                AZURE_CLIENT_ID: 1d742f67-369a-444f-b0f3-ab37a9190c48
                AZURE_CLIENT_SECRET: e_jXgwQicuE4l4Dyo4v.2_3aZxM5PL9V.P
                CSM_API_URL: https://api.comostech.com///latest
                CSM_DATASET_ABSOLUTE_PATH: /mnt/scenariorun-data
                CSM_PARAMETERS_ABSOLUTE_PATH: /mnt/scenariorun-parameters
                CSM_RUN_TEMPLATE_ID: hundred
                CSM_CONTAINER_MODE: postrun
                CSM_CONTROL_PLANE_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery-scenariorun
                CSM_PROBES_MEASURES_TOPIC: amqps://csm-phoenix.servicebus.windows.net/o-x2qomvxpjx-brewery
                CSM_SIMULATION: DeployedSimulation
              entrypoint: entrypoint.py
              runArgs: null
              dependencies: null
    BrewerySearch:
      summary: Brewery search ScenarioRun example
      description: Brewery search ScenarioRun of Workspace 1 in Running state example
      value:
        workspaceId: "1"
        state: "Running"
    BreweryScenarioRunStartContainers:
      summary: Brewery start ScenarioRun directly with containers example
      description: Brewery start ScenarioRun directly with containers example
      value:
        generateName: workflow-
        nodeLabel: highcpupool
        containers:
          fetchDatasetContainers:
            envVars:
              AZURE_TENANT_ID: "12345678"
              AZURE_CLIENT_ID: "12345678"
              AZURE_CLIENT_SECRET: azertyuiop
              CSM_API_URL: https://api.comostech.com
              CSM_API_TOKEN: azertyuiopqsdfghjklm
              ADT_INSTANCE_URL: https://supply.api.weu.digitaltwins.azure.net
              ADT_QUERY: SELECT * FROM digitaltwins
              CSM_DATASET_ABSOLUTE_PATH: /mnt/scenariorun-data
            image: csmphoenix.azurecr.io/azure-digital-twins-simulator-connector:latest
            name: fetchDatasetContainers
          sendDataWarehouseContainer:
            name: qsdfghjklm
            envVars:
              AZURE_TENANT_ID: "12345678"
              AZURE_CLIENT_ID: "12345678"
              AZURE_CLIENT_SECRET: azertyuiop
              CSM_API_URL: https://api.comostech.com
              CSM_API_TOKEN: azertyuiopqsdfghjklm
              CSM_DATASET_ABSOLUTE_PATH: /mnt/scenariorun-data
              CSM_PARAMETERS_ABSOLUTE_PATH: /mnt/scenariorun-parameters
              CSM_SEND_DATAWAREHOUSE_PARAMETERS: true
              CSM_SEND_DATAWAREHOUSE_DATASETS: true
              ADX_DATA_INGESTION_URI: https://ingest-phoenix.westeurope.kusto.windows.net
              ADX_DATABASE: Brewery
            image: csmphoenix.azurecr.io/azure-data-explorer-scenariorun-sender:latest
          runContainer:
            name: wxcvbn
            envVars:
              AZURE_TENANT_ID: "12345678"
              AZURE_CLIENT_ID: "12345678"
              AZURE_CLIENT_SECRET: azertyuiop
              CSM_API_URL: https://api.comostech.com
              CSM_API_TOKEN: azertyuiopqsdfghjklm
              CSM_ENGINE_PROVIDER: local
              CSM_ENGINE_PATH: run_templates/hundred/engine/
              CSM_DATASET_ABSOLUTE_PATH: /mnt/scenariorun-data
              CSM_PARAMETERS_ABSOLUTE_PATH: /mnt/scenariorun-parameters
              CSM_CONTROL_PLANE_TOPIC: amqps://csm-phoenix.servicebus.windows.net/organizationid-brewery-scenariorun
              CSM_PROBES_MEASURES_TOPIC: amqps://csm-phoenix.servicebus.windows.net/organizationid-brewery
              CSM_CONTAINER_MODE: engine
              CSM_SIMULATION: DeployedScenarioRun
            image: twinengines.azurecr.io/brewery_simulator:latest
            entrypoint: entrypoint.py
    BreweryScenarioRunLogs:
      summary: Brewery ScenarioRun logs  example
      description: Brewery ScenarioRun logs with plain text example
      value:
        scenariorunId: "1"
        containers: 
          fetchDatasetContainers:
            nodeId: azertyuiop-123
            containerName: azertyuiop
            children:
              - wxcvbn
            logs: cannot read source file
          runLogs:
            nodeid: wxcvbn-123
            containerName: wxcvbn
            logs: cannot run solution
    BreweryScenarioRunStatus:
      summary: Brewery status example
      description: Brewery Scenario Run status example
      value:
        id: SR-bDMr5lM9Vp
        organizationId: O-x2QOMVXpjX
        workflowId: 07193ced-9895-444f-b2be-31e8bfc3e768
        workflowName: workflow-s-eeypwem0kw-lsczk
        startTime: "2021-05-18T16:15:29.000Z"
        endTime: "2021-05-18T16:17:07.000Z"
        phase: Succeeded
        progress: 5/5
        message: null
        estimatedDuration: null
        nodes:
          - id: workflow-s-eeypwem0kw-lsczk
            name: workflow-s-eeypwem0kw-lsczk
            displayName: workflow-s-eeypwem0kw-lsczk
            estimatedDuration: null
            hostNodeName: null
            message: null
            phase: Succeeded
            progress: 5/5
            startTime: "2021-05-18T16:15:29.000Z"
            endTime: "2021-05-18T16:17:07.000Z"
          - id: workflow-s-eeypwem0kw-lsczk-1050490228
            name: workflow-s-eeypwem0kw-lsczk.applyParametersContainer
            displayName: applyParametersContainer
            estimatedDuration: null
            hostNodeName: phoenix-worker
            message: null
            phase: Succeeded
            progress: 1/1
            startTime: "2021-05-18T16:15:29.000Z"
            endTime: "2021-05-18T16:15:43.000Z"
          - id: workflow-s-eeypwem0kw-lsczk-1339592929
            name: workflow-s-eeypwem0kw-lsczk.postRunContainer
            displayName: postRunContainer
            estimatedDuration: null
            hostNodeName: phoenix-worker
            message: null
            phase: Succeeded
            progress: 1/1
            startTime: "2021-05-18T16:16:45.000Z"
            endTime: "2021-05-18T16:16:57.000Z"
          - id: workflow-s-eeypwem0kw-lsczk-2556449795
            name: workflow-s-eeypwem0kw-lsczk.runContainer
            displayName: runContainer
            estimatedDuration: null
            hostNodeName: null
            message: null
            phase: Succeeded
            progress: 1/1
            startTime: "2021-05-18T16:16:35.000Z"
            endTime: "2021-05-18T16:16:42.000Z"
          - id: workflow-s-eeypwem0kw-lsczk-545137412
            name: workflow-s-eeypwem0kw-lsczk.preRunContainer
            displayName: preRunContainer
            estimatedDuration: null
            hostNodeName: phoenix-worker
            message: null
            phase: Succeeded
            progress: 1/1
            startTime: "2021-05-18T16:16:13.000Z"
            endTime: "2021-05-18T16:16:25.000Z"
          - id: workflow-s-eeypwem0kw-lsczk-996178104
            name: workflow-s-eeypwem0kw-lsczk.validateDataContainer
            displayName: validateDataContainer
            estimatedDuration: null
            hostNodeName: phoenix-worker
            message: null
            phase: Succeeded
            progress: 1/1
            startTime: "2021-05-18T16:15:53.000Z"
            endTime: "2021-05-18T16:16:03.000Z"
