openapi: 3.0.3

info:
  title: Cosmo Tech Runner Manager API
  description: Cosmo Tech Runner Manager API
  version: 0.0.8-SNAPSHOT

servers:
- url: 'https://api.azure.cosmo-platform.com'
- url: 'http://localhost:4010'

security:
- oAuth2AuthCode: [ ]

tags:
- name: runner
  description: Runner Management

paths:
  /organizations/{organization_id}/workspaces/{workspace_id}/runners:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
    post:
      operationId: createRunner
      tags:
        - runner
      summary: Create a new Runner
      requestBody:
        description: the Runner to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Runner'
            examples:
              MasterRunner:
                $ref: '#/components/examples/BreweryRunnerIn'
              ChildRunner:
                $ref: '#/components/examples/BreweryChildRunnerIn'
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              MasterRunner:
                $ref: '#/components/examples/BreweryRunnerIn'
              ChildRunner:
                $ref: '#/components/examples/BreweryChildRunnerIn'
      responses:
        "201":
          description: the runner details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Runner'
              examples:
                Runner:
                  $ref: '#/components/examples/BreweryRunner'
        "400":
          description: Bad request
    get:
      operationId: findAllRunners
      parameters:
        - name: page
          in: query
          description: page number to query
          required: false
          schema:
            type: integer
        - name: size
          in: query
          description: amount of result by page
          required: false
          schema:
            type: integer
      tags:
        - runner
      summary: List all Runners
      responses:
        "200":
          description: the list of Runners
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Runner'
              examples:
                ThreeRunner:
                  $ref: '#/components/examples/ThreeRunners'

  /organizations/{organization_id}/workspaces/{workspace_id}/runners/{runner_id}:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
      - name: runner_id
        in: path
        description: the Runner identifier
        required: true
        schema:
          type: string
    get:
      operationId: findRunnerById
      tags:
        - runner
      summary: Get the details of an runner
      responses:
        "200":
          description: the Runner details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Runner'
              examples:
                Runner:
                  $ref: '#/components/examples/BreweryRunner'
        "404":
          description: the Runner specified is unknown or you don't have access to it
    patch:
      operationId: updateRunner
      tags:
        - runner
      summary: Update a runner
      requestBody:
        description: the new Runner details. This endpoint can't be used to update security
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Runner'
            examples:
              BreweryUpdate:
                $ref: '#/components/examples/BreweryRunnerUpdate'
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              BreweryUpdate:
                $ref: '#/components/examples/BreweryRunnerUpdate'
      responses:
        "200":
          description: the runner details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Runner'
              examples:
                BreweryUpdated:
                  $ref: '#/components/examples/BreweryRunnerUpdated'
        "400":
          description: Bad request
        "404":
          description: the Runner specified is unknown or you don't have access to it
    delete:
      operationId: deleteRunner
      tags:
        - runner
      summary: Delete a runner
      responses:
        "204":
          description: Request succeeded
        "404":
          description: the Runner specified is unknown or you don't have access to it

  /organizations/{organization_id}/workspaces/{workspace_id}/runners/{runner_id}/permissions/{role}:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
      - name: runner_id
        in: path
        description: the Runner identifier
        required: true
        schema:
          type: string
      - name: role
        in: path
        description: the Role
        required: true
        schema:
          type: string
    get:
      operationId: getRunnerPermissions
      tags:
        - runner
      summary: Get the Runner permission by given role
      responses:
        "200":
          description: The Runners security permission list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                  - "delete"
                  - "write"
                  - "createchildren"

  /organizations/{organization_id}/workspaces/{workspace_id}/runners/{runner_id}/security:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
      - name: runner_id
        in: path
        description: the Runner identifier
        required: true
        schema:
          type: string
    get:
      operationId: getRunnerSecurity
      tags:
        - runner
      summary: Get the Runner security information
      responses:
        "200":
          description: The Runner security
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunnerSecurity'
              examples:
                RunnerSecurity:
                  $ref: '#/components/examples/BreweryRunnerSecurity'
        "404":
          description: the Runner specified is unknown or you don't have access to it

  /organizations/{organization_id}/workspaces/{workspace_id}/runners/{runner_id}/security/default:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
      - name: runner_id
        in: path
        description: the Runner identifier
        required: true
        schema:
          type: string
    post:
      operationId: setRunnerDefaultSecurity
      tags:
        - runner
      summary: Set the Runner default security
      requestBody:
        description: This change the runner default security.
          The default security is the role assigned to any person not on the Access Control List.
          If the default security is None, then nobody outside of the ACL can access the runner.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunnerRole'
            examples:
              BreweryRunnerRole:
                $ref: '#/components/examples/BreweryRunnerRole'
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              BreweryRunnerRole:
                $ref: '#/components/examples/BreweryRunnerRole'
      responses:
        "201":
          description: The Runner default visibility
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunnerSecurity'
              examples:
                NoneRunnerSecurity:
                  $ref: '#/components/examples/BreweryDefaultSecurityRoleNone'
                WriterRunnerSecurity:
                  $ref: '#/components/examples/BreweryDefaultSecurityRoleWriter'
        "404":
          description: the Runner specified is unknown or you don't have access to it

  /organizations/{organization_id}/workspaces/{workspace_id}/runners/{runner_id}/security/access:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
      - name: runner_id
        in: path
        description: the Runner identifier
        required: true
        schema:
          type: string
    post:
      operationId: addRunnerAccessControl
      tags:
        - runner
      summary: Add a control access to the Runner
      requestBody:
        description: the new Runner security access to add.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunnerAccessControl'
            examples:
              RunnerAccess:
                $ref: '#/components/examples/BreweryRunnerAccessControl'
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              RunnerAccess:
                $ref: '#/components/examples/BreweryRunnerAccessControl'
      responses:
        "201":
          description: The Runner access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunnerAccessControl'
              examples:
                RunnerAccessControl:
                  $ref: '#/components/examples/BreweryRunnerAccessControl'
        "404":
          description: the Runner specified is unknown or you don't have access to it

  /organizations/{organization_id}/workspaces/{workspace_id}/runners/{runner_id}/security/access/{identity_id}:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
      - name: runner_id
        in: path
        description: the Runner identifier
        required: true
        schema:
          type: string
      - name: identity_id
        in: path
        description: the User identifier
        required: true
        schema:
          type: string
    get:
      operationId: getRunnerAccessControl
      tags:
        - runner
      summary: Get a control access for the Runner
      responses:
        "200":
          description: The Runner access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunnerAccessControl'
              examples:
                RunnerAccessControl:
                  $ref: '#/components/examples/BreweryRunnerAccessControl'
        "404":
          description: the Runner or user specified is unknown or you don't have access to it
    patch:
      operationId: updateRunnerAccessControl
      tags:
        - runner
      summary: Update the specified access to User for a Runner
      requestBody:
        description: The new Runner Access Control
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunnerRole'
            examples:
              BreweryRunnerRole:
                $ref: '#/components/examples/BreweryRunnerRole'
      responses:
        "200":
          description: The Runner access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunnerAccessControl'
              examples:
                RunnerAccessControl:
                  $ref: '#/components/examples/BreweryRunnerAccessControl'
        "404":
          description: The Organization specified is unknown or you don't have access to it
    delete:
      operationId: removeRunnerAccessControl
      tags:
        - runner
      summary: Remove the specified access from the given Organization Runner
      responses:
        "204":
          description: Request succeeded
        "404":
          description: the Runner or the user specified is unknown or you don't have access to them

  /organizations/{organization_id}/workspaces/{workspace_id}/runners/{runner_id}/security/users:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
      - name: runner_id
        in: path
        description: the Runner identifier
        required: true
        schema:
          type: string
    get:
      operationId: getRunnerSecurityUsers
      tags:
        - runner
      summary: Get the Runner security users list
      responses:
        "200":
          description: The Runner security users list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                  - alice@mycompany.com
                  - bob@mycompany.com
        "404":
          description: the Runner specified is unknown or you don't have access to it


components:
  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: OAuth2 authentication
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          scopes:
            http://dev.api.cosmotech.com/platform: Platform scope
  schemas:
    Runner:
      type: object
      x-class-extra-annotation: "@com.redis.om.spring.annotations.Document"
      description: a Runner with base information
      properties:
        id:
          type: string
          x-field-extra-annotation: "@org.springframework.data.annotation.Id"
          readOnly: true
          description: the Runner unique identifier
        name:
          type: string
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Searchable"
          description: the Runner name
        description:
          type: string
          description: the Runner description
        tags:
          type: array
          description: the list of tags
          items:
            type: string
        parentId:
          type: string
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          description: the Runner parent id
        ownerId:
          type: string
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          readOnly: true
          description: the user id which own this Runner
        rootId:
          type: string
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          readOnly: true
          description: the runner root id
        solutionId:
          type: string
          readOnly: true
          description: the Solution Id associated with this Runner
        runTemplateId:
          type: string
          description: the Solution Run Template Id associated with this Runner
        organizationId:
            type: string
            x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
            readOnly: true
            description: the associated Organization Id
        workspaceId:
          type: string
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          readOnly: true
          description: the associated Workspace Id
        state:
          $ref: '#/components/schemas/RunnerJobState'
        creationDate:
          type: integer
          format: int64
          readOnly: true
          description: the Runner creation date
        lastUpdate:
          type: integer
          format: int64
          readOnly: true
          description: the last time a Runner was updated
        ownerName:
          type: string
          readOnly: true
          description: the name of the owner
        solutionName:
          type: string
          readOnly: true
          description: the Solution name
        runTemplateName:
          type: string
          readOnly: true
          description: the Solution Run Template name associated with this Runner
        datasetList:
          type: array
          description: the list of Dataset Id associated to this Runner Run Template
          items:
            type: string
        runSizing:
          description: definition of resources needed for the runner run
          $ref: "#/components/schemas/RunnerResourceSizing"
        parametersValues:
          type: array
          description: the list of Solution Run Template parameters values
          items:
            $ref: '#/components/schemas/RunnerRunTemplateParameterValue'
        lastRun:
          allOf:
            - $ref: '#/components/schemas/RunnerLastRun'
            - type: object
              description: the last Runner Run for this Runner
        parentLastRun:
          allOf:
            - $ref: '#/components/schemas/RunnerLastRun'
            - type: object
              description: the last Runner Run for the parent of this Runner
        rootLastRun:
          allOf:
            - $ref: '#/components/schemas/RunnerLastRun'
            - type: object
              description: the last Runner Run for the root (master) of Runner
        validationStatus:
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Searchable"
          allOf:
            - $ref: '#/components/schemas/RunnerValidationStatus'
        security:
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          allOf:
            - $ref: '#/components/schemas/RunnerSecurity'
#      required:
#        - name
#        - runTemplateId
    RunnerSecurity:
      type: object
      description: the Runner security information
      properties:
        default:
          type: string
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          description: the role by default
        accessControlList:
          type: array
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          description: the list which can access this Runner with detailed access control information
          items:
            $ref: '#/components/schemas/RunnerAccessControl'
      required:
        - default
        - accessControlList
    RunnerAccessControl:
      type: object
      description: a Runner access control item
      properties:
        id:
          type: string
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          description: the identity id
        role:
          type: string
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          description: a role
      required:
        - id
        - role
    RunnerRole:
      type: object
      description: the Runner Role
      properties:
        role:
          type: string
          description: the Runner Role
      required:
        - role
    RunnerResourceSizing:
      type: object
      description: a description object for resource requests and limits (default same configuration as basic sizing)
      properties:
        requests:
          $ref: '#/components/schemas/ResourceSizeInfo'
        limits:
          $ref: '#/components/schemas/ResourceSizeInfo'
      required:
        - requests
        - limits
    ResourceSizeInfo:
      type: object
      description: define cpus and memory needs
      properties:
        cpu:
          type: string
          description: define cpu needs
        memory:
          type: string
          description: define memory needs
      required:
        - cpu
        - memory
    RunnerLastRun:
      type: object
      properties:
        runnerRunId:
          type: string
          description: the last Runner Run id
        csmSimulationRun:
          type: string
          description: the last Cosmo Tech Simulation Run id
        workflowId:
          type: string
          description: the last Workflow Id
        workflowName:
          type: string
          description: the last Workflow name
    RunnerRunTemplateParameterValue:
      type: object
      description: the value of a Solution Run Template parameter for a Runner
      properties:
        parameterId:
          type: string
          description: the parameter Id
        varType:
          type: string
          readOnly: true
          description: the parameter value type
        value:
          type: string
          description: the parameter value
        isInherited:
          type: boolean
          description: whether or not the value is inherited from parent or has been changed
      required:
        - parameterId
        - value
    RunnerComparisonResult:
      type: object
      description: the result of the comparison of two runners
      properties:
        runnerId:
          type: string
          readOnly: true
          description: the Runner Id which is the reference for the comparison
        comparedRunnerId:
          type: string
          readOnly: true
          description: the Runner Id the reference Runner is compared to
        changedValues:
          type: array
          readOnly: true
          description: the list of changed values for parameters
          items:
            $ref: '#/components/schemas/RunnerChangedParameterValue'
    RunnerChangedParameterValue:
      type: object
      description: the difference between the values of a parameter
      properties:
        parameterId:
          type: string
          readOnly: true
          description: the parameter id the values refer to
        varType:
          type: string
          readOnly: true
          description: the parameter value type
        value:
          type: string
          readOnly: true
          description: the parameter value for the reference Runner
        comparedValue:
          type: string
          readOnly: true
          description: the parameter value for the compared Runner
    RunnerDataDownloadInfo:
      type: object
      description: Runner data download job info
      properties:
        url:
          type: string
          readOnly: true
          description: the Runner Data Download URL
        state:
          $ref: '#/components/schemas/RunnerJobState'
    RunnerDataDownloadJob:
      type: object
      description: Runner data download job
      properties:
        id:
          type: string
          readOnly: true
          description: the Runner Data Download job identifier
    RunnerJobState:
      type: string
      readOnly: true
      description: the Runner job state
      enum:
        - Created
        - Running
        - Successful
        - Failed
        # PROD-7888 : When requesting the runner state right after a run has been submitted,
        # the runner run service (e.g., Argo Workflow) might not have scheduled the run
        # effectively yet.
        # Furthermore, temporary communication errors might occur anytime when remotely
        # fetching last runner run statuses.
        - Unknown
        # PROD-7420 : return data ingestion status
        - DataIngestionInProgress
    RunnerValidationStatus:
      type: string
      description: the validation status of the runner
      enum:
        - Draft
        - Rejected
        - Unknown
        - Validated
  examples:
    BreweryRunnerIn:
      summary: Brewery Runner input example
      description: Brewery Runner input example
      value:
        name: Brewery Master Analysis
        description: Brewery master reference analysis
        tags:
          - Brewery
          - reference
        runTemplateId: "hundred"
        datasetList:
          - "1"
        parametersValues:
          - parameterId: prefix
            varType: string
            value: ""
        security:
          default: "viewer"
          accessControlList:
            - id: "alice.doe@cosmotech.com"
              role: "admin"
    BreweryChildRunnerIn:
      summary: Brewery Child Runner input example
      description: Brewery Child Runner input example
      value:
        name: Brewery Child Analysis
        description: Brewery child reference analysis
        tags:
          - Brewery
        runTemplateId: "hundred"
        parentId: "1"
    BreweryRunner:
      summary: Brewery Runner
      description: Brewery Runner example
      value:
        id: "1"
        name: Brewery Master Analysis
        description: Brewery master reference analysis
        tags:
          - Brewery
          - reference
        ownerId: "1"
        worskspaceId: "1"
        solutionId: "1"
        solutionName: Brewery Solution
        runTemplateId: "hundred"
        runTemplateName: Full simulation 100 steps
        state: Running
        ownerName: Bob
        creationDate: "2021-04-21T17:32:28Z"
        lastUpdate: "2021-04-21T17:32:28Z"
        datasetList:
          - "1"
        parametersValues:
          - parameterId: prefix
            varType: string
            value: ""
        lastRun:
          csmSimulationRun: "ae8d1959-7a71-48ec-9f33-3fae53358cf1"
          runnerRunId: "SR-V9EYbbOE0"
          workflowId: "c7cd3f15-8a3b-4bcd-b3ca-62ee24c13d67"
          workflowName: "workflow-s-dwpxbzmdxn-zkvd7"
        security:
          default: "viewer"
          accessControlList:
            - id: "alice.doe@cosmotech.com"
              role: "admin"
    ThreeRunners:
      summary: Three Runners with parent and children
      description: Three Runners with parent master Runner and two children Runners
      value:
        - id: "1"
          name: Brewery Master Analysis
          description: Brewery master reference analysis
          tags:
            - Brewery
            - reference
          ownerId: "1"
          worskspaceId: "1"
          solutionId: "1"
          solutionName: Brewery Solution
          runTemplateId: "hundred"
          runTemplateName: Full simulation 100 steps
          state: Created
          ownerName: Bob
          creationDate: "2021-04-21T17:32:28Z"
          lastUpdate: "2021-04-21T17:32:28Z"
          datasetList:
            - "1"
          parametersValues:
            - parameterId: prefix
              varType: string
              value: ""
          security:
            default: "viewer"
            accessControlList:
              - id: "alice.doe@cosmotech.com"
                role: "admin"
        - id: "2"
          name: Brewery Analysis name example
          description: Brewery analysis with example as name prefix
          tags:
            - Brewery
            - example
          parentId: "1"
          ownerId: "1"
          worskspaceId: "1"
          solutionId: "1"
          solutionName: Brewery Solution
          runTemplateId: "hundred"
          runTemplateName: Full simulation 100 steps
          state: Running
          ownerName: Bob
          creationDate: "2021-04-21T17:32:28Z"
          lastUpdate: "2021-04-21T17:32:28Z"
          datasetList:
            - "1"
          parametersValues:
            - parameterId: prefix
              varType: string
              value: example
          lastRun:
            csmSimulationRun: "ae8d1959-7a71-48ec-9f33-3fae53358cf1"
            runnerRunId: "SR-V9EYbbOE0"
            workflowId: "c7cd3f15-8a3b-4bcd-b3ca-62ee24c13d67"
            workflowName: "workflow-s-dwpxbzmdxn-zkvd7"
          security:
            default: "viewer"
            accessControlList:
              - id: "alice.doe@cosmotech.com"
                role: "admin"
        - id: "3"
          name: Brewery Analysis name no change
          description: Brewery analysis with no change on name prefix
          tags:
            - Brewery
          parentId: "1"
          ownerId: "2"
          worskspaceId: "1"
          solutionId: "1"
          solutionName: Brewery Solution
          runTemplateId: "hundred"
          runTemplateName: Full simulation 100 steps
          state: Failed
          ownerName: Alice
          creationDate: "2021-04-21T17:32:28Z"
          lastUpdate: "2021-04-21T17:32:28Z"
          datasetList:
            - "1"
          parametersValues:
            - parameterId: prefix
              varType: string
              value: ""
              inherited: true
          lastRun:
            csmSimulationRun: "ae8d1959-7a71-48ec-9f33-3fae53358cf1"
            runnerRunId: "SR-V9EYbbOE0"
            workflowId: "c7cd3f15-8a3b-4bcd-b3ca-62ee24c13d67"
            workflowName: "workflow-s-dwpxbzmdxn-zkvd7"
          security:
            default: "viewer"
            accessControlList:
              - id: "alice.doe@cosmotech.com"
                role: "admin"
    BreweryRunnerUpdate:
      summary: Update the Brewery Runner
      description: Update the Brewery Runner by changing its name
      value:
        name: Brewery Master Analysis 2021
    BreweryRunnerUpdated:
      summary: Brewery updated Runner
      description: Brewery updated Runner example
      value:
        id: "1"
        name: Brewery Master Analysis 2021
        description: Brewery master reference analysis
        tags:
          - Brewery
          - reference
        ownerId: "1"
        worskspaceId: "1"
        solutionId: "1"
        solutionName: Brewery Solution
        runTemplateId: "hundred"
        runTemplateName: Full simulation 100 steps
        state: Created
        ownerName: Bob
        creationDate: "2021-04-21T17:32:28Z"
        lastUpdate: "2021-04-21T17:32:28Z"
        datasetList:
          - "1"
        parametersValues:
          - parameterId: prefix
            varType: string
            value: ""
        security:
          default: "viewer"
          accessControlList:
            - id: "alice.doe@cosmotech.com"
              role: "admin"
    BreweryRunnerComparison:
      summary: Brewery comparison result
      description: Brewery comparison result between a parent Runner and its child
      value:
        runnerId: "1"
        comparedRunnerId: "2"
        changedValues:
          - parameterId: prefix
            varType: string
            value: Brewery Master Analysis
            comparedValue: Brewery Master Analysis 2021
    RunnersTree:
      summary: Runners Tree example
      description: Runners Tree example with 1 master Runner and 2 children
      value:
        - id: "1"
          name: Brewery Master Analysis
          description: Brewery master reference analysis
          version: "1.0.0"
          tags:
            - Brewery
            - reference
          ownerId: "1"
          worskspaceId: "1"
          state: Created
          creationDate: "2021-04-21T17:32:28Z"
          lastUpdate: "2021-04-21T17:32:28Z"
          ownerName: Alice
          runTemplateName: Full simulation 100 steps
          solutionName: Brewery Solution
          datasetList:
            - "1"
          parametersValues:
            - parameterId: prefix
              varType: string
              value: ""
              inherited: true
          security:
            default: "viewer"
            accessControlList:
              - id: "alice.doe@cosmotech.com"
                role: "admin"
        - id: "2"
          name: Brewery Analysis name example
          description: Brewery analysis with example as name prefix
          tags:
            - Brewery
            - example
          parentId: "1"
          ownerId: "1"
          worskspaceId: "1"
          state: Running
          creationDate: "2021-04-21T17:32:28Z"
          lastUpdate: "2021-04-21T17:32:28Z"
          ownerName: Alice
          runTemplateName: Full simulation 100 steps
          solutionName: Brewery Solution
          datasetList:
            - "1"
          parametersValues:
            - parameterId: prefix
              varType: string
              value: ""
              inherited: true
          lastRun:
            csmSimulationRun: "ae8d1959-7a71-48ec-9f33-3fae53358cf1"
            runnerRunId: "SR-V9EYbbOE0"
            workflowId: "c7cd3f15-8a3b-4bcd-b3ca-62ee24c13d67"
            workflowName: "workflow-s-dwpxbzmdxn-zkvd7"
          security:
            default: "viewer"
            accessControlList:
              - id: "alice.doe@cosmotech.com"
                role: "admin"
        - id: "3"
          name: Brewery Analysis name no change
          description: Brewery analysis with no change on name prefix
          tags:
            - Brewery
          parentId: "1"
          ownerId: "2"
          worskspaceId: "1"
          state: Failed
          creationDate: "2021-04-21T17:32:28Z"
          lastUpdate: "2021-04-21T17:32:28Z"
          ownerName: Alice
          runTemplateName: Full simulation 100 steps
          solutionName: Brewery Solution
          datasetList:
            - "1"
          parametersValues:
            - parameterId: prefix
              varType: string
              value: ""
              inherited: true
          lastRun:
            csmSimulationRun: "ae8d1959-7a71-48ec-9f33-3fae53358cf1"
            runnerRunId: "SR-V9EYbbOE0"
            workflowId: "c7cd3f15-8a3b-4bcd-b3ca-62ee24c13d67"
            workflowName: "workflow-s-dwpxbzmdxn-zkvd7"
          security:
            default: "viewer"
            accessControlList:
              - id: "alice.doe@cosmotech.com"
                role: "admin"
    TwoRunnerRunTemplateParameterValueToAddOrReplace:
      summary: Runners Run Templates added
      description: Runners Run Templates added
      value:
        - parameterId: prefix
          varType: string
          value: ""
          inherited: true
        - parameterId: prefix2
          varType: string
          value: ""
          inherited: true
    BreweryRunnerDataDownloadJob:
      summary: Example of a runner data download job
      description: Brewery Runner Data Download Job
      value:
        id: "sdl-abc123defghi"
    BreweryRunnerSecurity:
      summary: Brewery Runner security
      description: Brewery Runner security example
      value:
        default: "viewer"
        accessControlList:
          - id: "alice.doe@cosmotech.com"
            role: "editor"
    BreweryRunnerRole:
      summary: Set a Runner Role.
      description: Set a Role for a User to a Runner.
      value:
        role: "editor"
    BreweryDefaultSecurityRoleNone:
      summary: Brewery Runner Writer default security
      description: Brewery Runner example
      value:
        default: "none"
    BreweryDefaultSecurityRoleWriter:
      summary: Brewery Runner Writer default security
      description: Brewery Runner example
      value:
        default: "editor"
    BreweryRunnerAccessControl:
      summary: Set an access control.
      description: Set an access control for a user to a workspace.
      value:
        id: "bob.doe@cosmotech.com"
        role: "editor"
