openapi: 3.0.3

info:
  title: Cosmo Tech Workspace Manager API
  description: Cosmo Tech Workspace Manager API
  version: 0.0.8-SNAPSHOT

servers:
- url: 'https://api.azure.cosmo-platform.com'
- url: 'http://localhost:4010'

security:
- oAuth2AuthCode: [ ]

tags:
- name: workspace
  description: Workspace Management

paths:
  /organizations/{organization_id}/workspaces:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
    post:
      operationId: createWorkspace
      tags:
        - workspace
      summary: Create a new workspace
      requestBody:
        description: the Workspace to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workspace'
            examples:
              Workspace:
                $ref: '#/components/examples/BreweryWorkspaceCreateIn'
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              Workspace:
                $ref: '#/components/examples/BreweryWorkspaceCreateIn'
      responses:
        "201":
          description: the workspace details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workspace'
              examples:
                Workspace:
                  $ref: '#/components/examples/BreweryWorkspace'
        "400":
          description: Bad request
    get:
      operationId: findAllWorkspaces
      tags:
        - workspace
      summary: List all Workspaces
      responses:
        "200":
          description: the workspace details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workspace'
              examples:
                OneWorkspace:
                  $ref: '#/components/examples/OneWorkspace'
  /organizations/{organization_id}/workspaces/{workspace_id}:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
    get:
      operationId: findWorkspaceById
      tags:
        - workspace
      summary: Get the details of an workspace
      responses:
        "200":
          description: the Workspace details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workspace'
              examples:
                Workspace:
                  $ref: '#/components/examples/BreweryWorkspace'
        "404":
          description: the Workspace specified is unknown or you don't have access to it
    patch:
      operationId: updateWorkspace
      tags:
        - workspace
      summary: Update a workspace
      requestBody:
        description: the new Workspace details.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workspace'
            examples:
              BreweryUpdate:
                $ref: '#/components/examples/BreweryWorkspaceUpdate'
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              BreweryUpdate:
                $ref: '#/components/examples/BreweryWorkspaceUpdate'
      responses:
        "200":
          description: the workspace details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workspace'
              examples:
                BreweryUpdated:
                  $ref: '#/components/examples/BreweryWorkspaceUpdated'
        "400":
          description: Bad request
        "404":
          description: the Workspace specified is unknown or you don't have access to it
    delete:
      operationId: deleteWorkspace
      tags:
        - workspace
      summary: Delete a workspace
      responses:
        "200":
          description: the workspace details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workspace'
              examples:
                Workspace:
                  $ref: '#/components/examples/BreweryWorkspace'
        "400":
          description: Bad request
        "404":
          description: the Workspace specified is unknown or you don't have access to it

  /organizations/{organization_id}/workspaces/{workspace_id}/files:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
    post:
      operationId: uploadWorkspaceFile
      tags:
        - workspace
      summary: Upload a file for the Workspace
      requestBody:
        description: the file to upload
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                overwrite:
                  type: boolean
                  default: false
                destination:
                  # PROD-7601 : Allow clients to specify where the file should be uploaded
                  type: string
                  description: |
                    Destination path. Must end with a '/' if specifying a folder.
                    Note that paths may or may not start with a '/', but they are always treated
                    as relative to the Workspace root location.
                  example: "path/to/a/directory/"
                file:
                  type: string
                  format: binary
              required:
                - file
            examples:
              use_file_name_as_is:
                summary: Use the file name as is as destination
                value:
                  file: "Lorem Ipsum Dolor Sit Amet"
              upload_to_workspace_root_under_a_different_file_name:
                summary: Upload to the Workspace root folder, but rename the target file
                value:
                  destination: "my_file_renamed.txt"
                  file: "Lorem Ipsum Dolor Sit Amet"
              upload_to_a_folder:
                summary: |
                  Upload to a sub-folder.
                  Destination may or may not start with a '/', but must end with '/' to be treated as a directory.
                  Final file path will always be relative to the Workspace root location.
                value:
                  destination: "path/to/a/directory/"
                  file: "Lorem Ipsum Dolor Sit Amet"
              upload_to_a_specific_folder_and_under_a_different_file_name:
                summary: |
                  Upload to a sub-folder.
                  Destination may or may not start with a '/', but must not end with '/'.
                  Final file path will always be relative to the Workspace root location.
                value:
                  destination: "/path/to/a/directory/my_file_renamed.txt"
                  file: "Lorem Ipsum Dolor Sit Amet"
      responses:
        "201":
          description: the file resource details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceFile'
              examples:
                BreweryWorkspaceFile:
                  $ref: '#/components/examples/BreweryWorkspaceFile'
        "400":
          description: Bad request
    get:
      operationId: findAllWorkspaceFiles
      tags:
        - workspace
      summary: List all Workspace files
      responses:
        "200":
          description: the workspace files
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkspaceFile'
              examples:
                WorkspaceFiles:
                  $ref: '#/components/examples/WorkspaceFiles'
        "404":
          description: the Workspace specified is unknown or you don't have access to it
    delete:
      operationId: deleteAllWorkspaceFiles
      tags:
        - workspace
      summary: Delete all Workspace files
      responses:
        "204":
          description: Request succeeded
        "404":
          description: the Workspace specified is unknown or you don't have access to them

  /organizations/{organization_id}/workspaces/{workspace_id}/files/download:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
      - name: file_name
        in: query
        description: the file name
        required: true
        schema:
          type: string
    get:
      operationId: downloadWorkspaceFile
      tags:
        - workspace
      summary: Download the Workspace File specified
      responses:
        "200":
          description: the workspace file as a resource
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "404":
          description: the Workspace file specified is unknown or you don't have access to it

  /organizations/{organization_id}/workspaces/{workspace_id}/files/delete:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
      - name: file_name
        in: query
        description: the file name
        required: true
        schema:
          type: string
    delete:
      operationId: deleteWorkspaceFile
      tags:
        - workspace
      summary: Delete a workspace file
      responses:
        "204":
          description: Request succeeded
        "404":
          description: the Workspace or the file specified is unknown or you don't have access to them

  /organizations/{organization_id}/workspaces/{workspace_id}/users:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
    post:
      operationId: addOrReplaceUsersInOrganizationWorkspace
      tags:
        - workspace
      summary: Add (or replace) users to the Workspace specified
      requestBody:
        description: the Users to add. Any User with the same ID is overwritten
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/WorkspaceUser'
            examples:
              TwoWorkspaceUsersToAddOrReplace:
                $ref: '#/components/examples/TwoWorkspaceUsers'
      responses:
        "200":
          description: the Workspace Users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkspaceUser'
              examples:
                TwoWorkspaceUsers:
                  $ref: '#/components/examples/TwoWorkspaceUsers'
        "404":
          description: the Workspace specified is unknown or you don't have access to it
    delete:
      operationId: removeAllUsersOfWorkspace
      tags:
        - workspace
      summary: Remove all users from the Workspace specified
      responses:
        "204":
          description: the operation succeeded
        "404":
          description: the Workspace specified is unknown or you don't have access to it

  /organizations/{organization_id}/workspaces/{workspace_id}/users/{user_id}:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
      - name: user_id
        in: path
        description: the User identifier
        required: true
        schema:
          type: string
    delete:
      operationId: removeUserFromOrganizationWorkspace
      tags:
        - workspace
      summary: Remove the specified user from the given Organization Workspace
      responses:
        "204":
          description: Request succeeded
        "404":
          description: the Workspace or the User specified is unknown or you don't have access to them
  /organizations/{organization_id}/workspaces/{workspace_id}/secret:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: workspace_id
        in: path
        description: the Workspace identifier
        required: true
        schema:
          type: string
    post:
      operationId: createSecret
      tags:
        - workspace
      summary: Create a secret for the Workspace
      requestBody:
        description: the definition of the secret
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkspaceSecret'
            examples:
              Workspace:
                $ref: '#/components/examples/WorkspaceSecretExample'
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              Workspace:
                $ref: '#/components/examples/WorkspaceSecretExample'
      responses:
        "201":
          description: Request succeeded
        "404":
          description: the Workspace or the User specified is unknown or you don't have access to them
components:
  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: OAuth2 authentication
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          scopes:
            http://dev.api.cosmotech.com/platform: Platform scope
  schemas:
    Workspace:
      type: object
      description: a Workspace
      properties:
        id:
          type: string
          readOnly: true
          description: the Workspace version unique identifier
        key:
          type: string
          description: technical key for resource name convention and version grouping. Must be unique
        name:
          type: string
          description: the Workspace name
        description:
          type: string
          description: the Workspace description
        version:
          type: string
          description: the Workspace version MAJOR.MINOR.PATCH.
        tags:
          type: array
          description: the list of tags
          items:
            type: string
        ownerId:
          type: string
          readOnly: true
          description: the user id which own this workspace
        solution:
          $ref: '#/components/schemas/WorkspaceSolution'
        users:
          type: array
          description: the list of users Id with their role
          items:
            $ref: '#/components/schemas/WorkspaceUser'
        webApp:
          $ref: '#/components/schemas/WorkspaceWebApp'
        sendInputToDataWarehouse:
          type: boolean
          description: default setting for all Scenarios and Run Templates to set whether or not the Dataset values and the input parameters values are send to the DataWarehouse prior to the ScenarioRun
        useDedicatedEventHubNamespace:
          type: boolean
          default: false
          description: Set this property to true to use a dedicated Azure Event Hub Namespace for this Workspace.
            The Event Hub Namespace must be named \'<organization_id\>-<workspace_id\>\' (in lower case).
            This Namespace must also contain two Event Hubs named \'probesmeasures\' and \'scenariorun\'.
        dedicatedEventHubSasKeyName:
          type: string
          description: the Dedicated Event Hub SAS key name, default to RootManageSharedAccessKey. Use the /secret endpoint to set the key value
        dedicatedEventHubAuthenticationStrategy:
          type: string
          description: the Event Hub authentication strategy, SHARED_ACCESS_POLICY or TENANT_CLIENT_CREDENTIALS. Default to the one defined for the tenant.
        sendScenarioRunToEventHub:
          type: boolean
          default : true
          description: default setting for all Scenarios and Run Templates to set whether or not the ScenarioRun is send to the Event Hub
        sendScenarioMetadataToEventHub:
          type: boolean
          default: false
          description: Set this property to false to not send scenario metada to Azure Event Hub Namespace for this Workspace.
            The Event Hub Namespace must be named \'<organization_id\>-<workspace_id\>\' (in lower case).
            This Namespace must also contain two Event Hubs named \'scenariometadata\' and \'scenariorunmetadata\'.
      required:
        - key
        - name
        - solution
    WorkspaceUser:
      type: object
      description: a Workspace user with roles
      properties:
        id:
          type: string
          description: the User id
        name:
          type: string
          readOnly: true
          description: the User name
        roles:
          type: array
          description: the User roles
          items:
            type: string
            enum: ["Admin","User","Viewer"]
      required:
        - id
        - roles
    WorkspaceFile:
      type: object
      description: a Workspace File resource
      properties:
        fileName:
          type: string
          description: the Workspace File name
    WorkspaceWebApp:
      type: object
      description: a Workspace Web Application
      properties:
        url:
          type: string
          description: the Workspace Web Application URL
        iframes:
          type: object
          description: a map of iframeKey/iframeURL
          additionalProperties: true
        options:
          type: object
          description: free form options for Web Application
          additionalProperties: true
      required:
        - url
    WorkspaceSolution:
      type: object
      description: the Workspace Solution configuration
      properties:
        solutionId:
          type: string
          description: the Solution Id attached to this workspace
        runTemplateFilter:
          type: array
          description: the list of Solution Run Template Id to filter
          items:
            type: string
        defaultRunTemplateDataset:
          type: object
          description: a map of RunTemplateId/DatasetId to set a default dataset for a Run Template
          additionalProperties: true
      # required:
        # - solutionId
    WorkspaceSecret:
      type: object
      description: the secret definition
      properties:
        dedicatedEventHubKey:
          type: string
          description: the dedicated event hub shared access key
  examples:
    BreweryWorkspaceCreateIn:
      summary: Brewery Workspace Create input parameters example
      description: Brewery Workspace Create input parameters example
      value:
        name: Brewery Analysis
        key: brewery
        description: Brewery analysis for stock, production, transport and customer satisfaction
        version: "1.0.0"
        tags:
          - Brewery
        solution:
          solutionId: "1"
          runTemplateFilter:
            - "1"
          defaultRunTemplateDataset:
            1: "1"
        users:
          - id: "1"
            roles:
              - Admin
          - id: "2"
            roles:
              - Viewer
        webApp:
          url: https://brewery.app.cosmotech.com
          iframes:
            main: https://app.powerbi.com/reportEmbed?reportId=05eee4e7-b301-4fb3-8850-9ef00f3516ef&autoAuth=true&ctid=e9641c78-d0d6-4d09-af63-168922724e7f&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLWZyYW5jZS1jZW50cmFsLWEtcHJpbWFyeS1yZWRpcmVjdC5hbmFseXNpcy53aW5kb3dzLm5ldC8ifQ%3D%3D
            dashboard: https://app.powerbi.com/reportEmbed?reportId=05eee4e7-b301-4fb3-8850-9ef00f3516ef&autoAuth=true&ctid=e9641c78-d0d6-4d09-af63-168922724e7f&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLWZyYW5jZS1jZW50cmFsLWEtcHJpbWFyeS1yZWRpcmVjdC5hbmFseXNpcy53aW5kb3dzLm5ldC8ifQ%3D%3D
    BreweryWorkspace:
      summary: Brewery Workspace
      description: Brewery Workspace example
      value:
        id: "1"
        name: Brewery Analysis
        key: brewery
        description: Brewery analysis for stock, production, transport and customer satisfaction
        version: "1.0.0"
        tags:
          - Brewery
        ownerId: "1"
        solution:
          solutionId: "1"
          runTemplateFilter:
            - "1"
          defaultRunTemplateDataset:
            1: "1"
        users:
          - id: "1"
            name: Bob
            roles:
              - Admin
          - id: "2"
            name: Alice
            roles:
              - Viewer
        webApp:
          url: https://brewery.app.cosmotech.com
          iframes:
            main: https://app.powerbi.com/reportEmbed?reportId=05eee4e7-b301-4fb3-8850-9ef00f3516ef&autoAuth=true&ctid=e9641c78-d0d6-4d09-af63-168922724e7f&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLWZyYW5jZS1jZW50cmFsLWEtcHJpbWFyeS1yZWRpcmVjdC5hbmFseXNpcy53aW5kb3dzLm5ldC8ifQ%3D%3D
            dashboard: https://app.powerbi.com/reportEmbed?reportId=05eee4e7-b301-4fb3-8850-9ef00f3516ef&autoAuth=true&ctid=e9641c78-d0d6-4d09-af63-168922724e7f&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLWZyYW5jZS1jZW50cmFsLWEtcHJpbWFyeS1yZWRpcmVjdC5hbmFseXNpcy53aW5kb3dzLm5ldC8ifQ%3D%3D
    OneWorkspace:
      summary: One Workspace list
      description: One Workspace list example
      value:
        - id: "1"
          name: Brewery Analysis
          key: brewery
          description: Brewery analysis for stock, production, transport and customer satisfaction
          version: "1.0.0"
          tags:
            - Brewery
          ownerId: "1"
          solution:
            solutionId: "1"
            runTemplateFilter:
              - "1"
            defaultRunTemplateDataset:
              1: "1"
          users:
            - id: "1"
              name: Bob
              roles:
                - Admin
            - id: "2"
              name: Alice
              roles:
                - Viewer
          webApp:
            url: https://brewery.app.cosmotech.com
            iframes:
              main: https://app.powerbi.com/reportEmbed?reportId=05eee4e7-b301-4fb3-8850-9ef00f3516ef&autoAuth=true&ctid=e9641c78-d0d6-4d09-af63-168922724e7f&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLWZyYW5jZS1jZW50cmFsLWEtcHJpbWFyeS1yZWRpcmVjdC5hbmFseXNpcy53aW5kb3dzLm5ldC8ifQ%3D%3D
              dashboard: https://app.powerbi.com/reportEmbed?reportId=05eee4e7-b301-4fb3-8850-9ef00f3516ef&autoAuth=true&ctid=e9641c78-d0d6-4d09-af63-168922724e7f&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLWZyYW5jZS1jZW50cmFsLWEtcHJpbWFyeS1yZWRpcmVjdC5hbmFseXNpcy53aW5kb3dzLm5ldC8ifQ%3D%3D
    BreweryWorkspaceUpdate:
      summary: Update the Brewery Workspace
      description: Update the Brewery Workspace by changing its name
      value:
        name: Brewery Analysis 2021
    BreweryWorkspaceUpdated:
      summary: Brewery Workspace
      description: Brewery Workspace example
      value:
        id: "1"
        key: brewery
        name: Brewery Analysis 2021
        description: Brewery analysis for stock, production, transport and customer satisfaction
        version: "1.0.0"
        tags:
          - Brewery
        ownerId: "1"
        solution:
          solutionId: "1"
          runTemplateFilter:
            - "1"
          defaultRunTemplateDataset:
            1: "1"
        users:
          - id: "1"
            name: Bob
            roles:
              - Admin
          - id: "2"
            name: Alice
            roles:
              - Viewer
        webApp:
          url: https://brewery.app.cosmotech.com
          iframes:
            main: https://app.powerbi.com/reportEmbed?reportId=05eee4e7-b301-4fb3-8850-9ef00f3516ef&autoAuth=true&ctid=e9641c78-d0d6-4d09-af63-168922724e7f&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLWZyYW5jZS1jZW50cmFsLWEtcHJpbWFyeS1yZWRpcmVjdC5hbmFseXNpcy53aW5kb3dzLm5ldC8ifQ%3D%3D
            dashboard: https://app.powerbi.com/reportEmbed?reportId=05eee4e7-b301-4fb3-8850-9ef00f3516ef&autoAuth=true&ctid=e9641c78-d0d6-4d09-af63-168922724e7f&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLWZyYW5jZS1jZW50cmFsLWEtcHJpbWFyeS1yZWRpcmVjdC5hbmFseXNpcy53aW5kb3dzLm5ldC8ifQ%3D%3D
    BreweryWorkspaceFile:
      summary: Brewery Workspace file example
      description: Brewery Workspace file uploaded return example
      value:
        fileName: myData.csv
    WorkspaceFiles:
      summary: Brewery Workspace files example
      description: Brewery Workspace files example
      value:
        - fileName: myData.csv
        - fileName: myData2.csv
        - fileName: myData3.csv
    TwoWorkspaceUsers:
      summary: Two users of a Workspace
      description: Two Users of a Workspace example
      value:
        - id: "1"
          name: Bob
          roles:
            - Admin
        - id: "2"
          name: Alice
          roles:
            - User
    TwoWorkspaceToAddOrReplace:
      summary: Two users of a Workspace
      description: Two Users of a Workspace example
      value:
        - id: "1"
          roles:
            - Admin
        - id: "2"
          roles:
            - User
    WorkspaceSecretExample:
      summary: a shared access policy
      description: a shared policy example
      value:
        dedicatedEventHubKey: xxx
