openapi: 3.0.3

info:
  title: ""
  version: ""

security:
  - oAuth2AuthCode: []

tags:
- name: organization
  description: organization Management

paths:
  /organizations:
    post:
      operationId: createOrganization
      tags:
        - organization
      summary: Create a new organization
      requestBody:
        description: the organization to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationRequest'
            examples:
              NewOrganizationIn:
                $ref: '#/components/examples/NewOrganizationIn'
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              NewOrganizationIn:
                $ref: '#/components/examples/NewOrganizationIn'
      responses:
        "201":
          description: the organization details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
              examples:
                CosmoOrganization:
                  $ref: '#/components/examples/CosmoOrganization'
        "400":
          description: Bad request
    get:
      operationId: listOrganizations
      parameters:
        - name: page
          in: query
          description: page number to query (first page is at index 0)
          required: false
          schema:
            type: integer
        - name: size
          in: query
          description: amount of result by page
          required: false
          schema:
            type: integer
      tags:
        - organization
      summary: List all organizations
      responses:
        "200":
          description: the list of organizations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
              examples:
                TwoOrganizations:
                  $ref: '#/components/examples/TwoOrganizations'

  /organizations/{organization_id}:
    parameters:
      - name: organization_id
        in: path
        description: the organization identifier
        required: true
        schema:
          type: string
    get:
      operationId: getOrganization
      tags:
        - organization
      summary: Get the details of an organization
      responses:
        "200":
          description: the organization details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
              examples:
                CosmoOrganization:
                  $ref: '#/components/examples/CosmoOrganization'
        "404":
          description: the organization specified is unknown or you don't have access to it
    patch:
      operationId: updateOrganization
      tags:
        - organization
      summary: Update an organization
      requestBody:
        description: the new organization details. This endpoint can't be used to update security
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationUpdate'
            examples:
              ChangeName:
                summary: Change Name of organization
                description: Change the name of organization 1 to CosmoTech Digital Twins Engine
                value:
                  name: "CosmoTech Digital Twins Engine"
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              ChangeName:
                summary: Change Name of organization
                description: Change the name of organization 1 to CosmoTech Digital Twins Engine
                value:
                  name: "CosmoTech Digital Twins Engine"
      responses:
        "200":
          description: the organization details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
              examples:
                CosmoThreeUsers:
                  $ref: '#/components/examples/CosmoThreeUsers'
        "400":
          description: Bad request
        "404":
          description: the organization specified is unknown or you don't have access to it
    delete:
      operationId: deleteOrganization
      tags:
        - organization
      summary: Delete an organization
      responses:
        "204":
          description: Request succeeded
        "404":
          description: the organization specified is unknown or you don't have access to it

  /organizations/permissions:
    get:
      operationId: getAllPermissions
      tags:
        - organization
      summary: Get all permissions per components
      responses:
        "200":
          description: The security permission list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComponentRolePermissions'
              examples:
                permissions:
                  $ref: '#/components/examples/Permissions'


  /organizations/{organization_id}/permissions/{role}:
    parameters:
      - name: organization_id
        in: path
        description: the organization identifier
        required: true
        schema:
          type: string
      - name: role
        in: path
        description: the Role
        required: true
        schema:
          type: string
    get:
      operationId: getOrganizationPermissions
      tags:
        - organization
      summary: Get the organization permissions by given role
      responses:
        "200":
          description: The organization security permission list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                  - "read"
                  - "read_security"
                  - "create_children"

  /organizations/{organization_id}/security:
    parameters:
      - name: organization_id
        in: path
        description: the organization identifier
        required: true
        schema:
          type: string
    get:
      operationId: getOrganizationSecurity
      tags:
        - organization
      summary: Get the organization security information
      responses:
        "200":
          description: The organization security
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationSecurity'
              examples:
                organizationSecurity:
                  $ref: '#/components/examples/BreweryOrganizationSecurity'
        "404":
          description: the organization specified is unknown or you don't have access to it

  /organizations/{organization_id}/security/default:
    parameters:
      - name: organization_id
        in: path
        description: the organization identifier
        required: true
        schema:
          type: string
    post:
      operationId: setOrganizationDefaultSecurity
      tags:
        - organization
      summary: Set the organization default security
      requestBody:
        description: This change the organization default security.
                    The default security is the role assigned to any person not on the Access Control List.
                    If the default security is None, then nobody outside of the ACL can access the organization.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationRole'
            examples:
              BreweryOrganizationRole:
                $ref: '#/components/examples/BreweryOrganizationRole'
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              BreweryOrganizationRole:
                $ref: '#/components/examples/BreweryOrganizationRole'
      responses:
        "201":
          description: The organization default visibility
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationSecurity'
              examples:
                WriterOrganizationSecurity:
                  $ref: '#/components/examples/BreweryDefaultSecurityRoleWriter'
        "404":
          description: the organization specified is unknown or you don't have access to it

  /organizations/{organization_id}/security/access:
    parameters:
      - name: organization_id
        in: path
        description: the organization identifier
        required: true
        schema:
          type: string
    post:
      operationId: addOrganizationAccessControl
      tags:
        - organization
      summary: Add a control access to the organization
      requestBody:
        description: the new organization security access to add.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationAccessControl'
            examples:
              organizationAccess:
                $ref: '#/components/examples/BreweryOrganizationAccessControl'
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              organizationAccess:
                $ref: '#/components/examples/BreweryOrganizationAccessControl'
      responses:
        "201":
          description: The organization access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationAccessControl'
              examples:
                organizationAccessControl:
                  $ref: '#/components/examples/BreweryOrganizationAccessControl'
        "404":
          description: the organization specified is unknown or you don't have access to it

  /organizations/{organization_id}/security/access/{identity_id}:
    parameters:
      - name: organization_id
        in: path
        description: the organization identifier
        required: true
        schema:
          type: string
      - name: identity_id
        in: path
        description: the User identifier
        required: true
        schema:
          type: string
    get:
      operationId: getOrganizationAccessControl
      tags:
        - organization
      summary: Get a control access for the organization
      responses:
        "200":
          description: The organization access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationAccessControl'
              examples:
                organizationAccessControl:
                  $ref: '#/components/examples/BreweryOrganizationAccessControl'
        "404":
          description: The organization or user specified is unknown or you don't have access to it
    patch:
      operationId: updateOrganizationAccessControl
      tags:
        - organization
      summary: Update the specified access to User for an organization
      requestBody:
        description: The new organization Access Control
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationRole'
            examples:
              BreweryOrganizationRole:
                $ref: '#/components/examples/BreweryOrganizationRole'
      responses:
        "200":
          description: The organization access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationAccessControl'
              examples:
                organizationAccessControl:
                  $ref: '#/components/examples/BreweryOrganizationAccessControl'
        "404":
          description: The organization specified is unknown or you don't have access to it
    delete:
      operationId: removeOrganizationAccessControl
      tags:
        - organization
      summary: Remove the specified access from the given organization
      responses:
        "204":
          description: Request succeeded
        "404":
          description: the organization or the user specified is unknown or you don't have access to them

  /organizations/{organization_id}/security/users:
    parameters:
      - name: organization_id
        in: path
        description: The organization identifier
        required: true
        schema:
          type: string
    get:
      operationId: getOrganizationSecurityUsers
      tags:
        - organization
      summary: Get the organization security users list
      responses:
        "200":
          description: The organization security users list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                  - alice@mycompany.com
                  - bob@mycompany.com
        "404":
          description: the organization specified is unknown or you don't have access to it

components:
  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: OAuth2 authentication
      flows:
        authorizationCode:
          authorizationUrl: "https://example.com/authorize"
          tokenUrl: "https://example.com/token"
          scopes: {}
  schemas:
    Organization:
      type: object
      x-class-extra-annotation: "@com.redis.om.spring.annotations.Document"
      description: an organization
      required:
        - id
        - ownerId
        - name
        - security
      properties:
        id:
          x-field-extra-annotation: "@org.springframework.data.annotation.Id"
          type: string
          description: the organization unique identifier
        ownerId:
          type: string
          description: the Owner User Id
      allOf:
        - $ref: '#/components/schemas/OrganizationRequest'
    OrganizationRequest:
      type: object
      description: Request to create an organization
      required:
        - name
      allOf:
        - $ref: '#/components/schemas/OrganizationUpdate'
      properties:
        security:
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          allOf:
            - $ref: '#/components/schemas/OrganizationSecurity'
    OrganizationUpdate:
      type: object
      description: Data to update an organization
      properties:
        name:
          type: string
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Searchable"
          description: the organization name
    OrganizationSecurity:
      type: object
      description: the organization security information
      properties:
        default:
          type: string
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          description: the role by default
        accessControlList:
          type: array
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          description: the list which can access this organization with detailed access control information
          items:
            $ref: '#/components/schemas/OrganizationAccessControl'
      required:
        - default
        - accessControlList
    OrganizationAccessControl:
      type: object
      description: a organization access control item
      properties:
        id:
          type: string
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          description: the identity id
        role:
          type: string
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          description: a role
      required:
        - id
        - role
    OrganizationRole:
      type: object
      description: the organization Role
      properties:
        role:
          type: string
          description: the organization Role
      required:
        - role
    ComponentRolePermissions:
      type: object
      description: a RBAC by component
      properties:
        component:
          type: string
        roles:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
  examples:
    NewOrganizationIn:
      summary: Create a new organization
      description: Create a new organization with 2 users
      value:
        name: Cosmo Tech
        security:
          default: reader
          accessControlList:
            - id: "jane.doe@cosmotech.com"
              role: "editor"
            - id: "john.doe@cosmotech.com"
              role: "viewer"
    CosmoOrganization:
      summary: Cosmo Tech organization example
      description: Cosmo Tech organization example
      value:
        id: "1"
        name: Cosmo Tech
        ownerId: "1"
        security:
          default: reader
          accessControlList:
            - id: "jane.doe@cosmotech.com"
              role: "editor"
            - id: "john.doe@cosmotech.com"
              role: "viewer"
    BreweryOrganizationSecurity:
      summary: Brewery organization security
      description: Brewery organization security example
      value:
        default: "viewer"
        accessControlList:
          - id: "bob@mycosmocompany.com"
            role: "editor"
    BreweryOrganizationAccessControl:
      summary: Set an access control.
      description: Set an access control for a user to an organization.
      value:
        id: "bob@mycompany.com"
        role: "editor"
    BreweryOrganizationRole:
      summary: Set an organization Role.
      description: Set an role for a user to an organization.
      value:
        role: "editor"
    CosmoThreeUsers:
      summary: Cosmo Tech organization with 3 users
      description: Cosmo Tech organization 3 users example
      value:
        id: "1"
        name: Cosmo Tech
        security:
          default: reader
          accessControlList:
            - id: "bob.doe@cosmotech.com"
              role: "viewer"
            - id: "alice.doe@cosmotech.com"
              role: "viewer"
            - id: "xavier.doe@cosmotech.com"
              role: "editor"
    TwoOrganizations:
      summary: Two Orgnizations
      description: Two organizations example
      value:
        - id: "1"
          name: Cosmo Tech
          ownerId: "1"
          security:
            default: reader
            accessControlList:
              - id: "bob.doe@cosmotech.com"
                role: "editor"
              - id: "alice.doe@cosmotech.com"
                role: "viewer"
        - id: "2"
          name: Phoenix
          security:
            default: rolereader
            accessControlList:
              - id: "bob.doe@cosmotech.com"
                role: "editor"
    BreweryDefaultSecurityRoleWriter:
      summary: Brewery Scenario Writer default security
      description: Brewery Scenario example
      value:
        default: "editor"
    Permissions:
      summary: Permissions
      description: Permissions for organization
      value:
        - component: organization
          roles:
            none: []
            viewer:
              - read
              - read_security
            user:
              - read
              - read_security
              - create_children
            editor:
              - read
              - read_security
              - create_children
              - write
            admin:
              - read
              - read_security
              - create_children
              - write
              - write_security
              - delete
        - component: workspace
          roles:
            none: []
            viewer:
              - read
              - read_security
            user:
              - read
              - read_security
              - create_children
            editor:
              - read
              - read_security
              - create_children
              - write
            admin:
              - read
              - read_security
              - create_children
              - write
              - write_security
              - delete
        - component: runner
          roles:
            none: []
            viewer:
              - read
              - read_security
            editor:
              - read
              - read_security
              - launch
              - write
            validator:
              - read
              - read_security
              - launch
              - write
              - validate
            admin:
              - read
              - read_security
              - launch
              - write
              - validate
              - write_security
              - delete

