openapi: 3.0.3

info:
  title: Cosmo Tech Dataset Manager API
  description: Cosmo Tech Dataset Manager API
  version: 0.0.8-SNAPSHOT

servers:
- url: 'https://dev.api.cosmotech.com'
- url: 'http://localhost:8080'

security:
- oAuth2AuthCode: [ ]

tags:
- name: dataset
  description: Dataset Management

paths:
  /organizations/{organization_id}/datasets:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
    post:
      operationId: createDataset
      tags:
        - dataset
      summary: Create a new Dataset
      requestBody:
        description: the Dataset to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dataset'
            examples:
              BreweryADT:
                $ref: '#/components/examples/BreweryADT'
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              BreweryADT:
                $ref: '#/components/examples/BreweryADT'
      responses:
        "201":
          description: the dataset details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
              examples:
                BreweryADT:
                  $ref: '#/components/examples/BreweryADT'
        "400":
          description: Bad request
    get:
      parameters:
        - name: page
          in: query
          description: page number to query
          required: false
          schema:
            type: integer
        - name: size
          in: query
          description: amount of result by page
          required: false
          schema:
            type: integer
      operationId: findAllDatasets
      tags:
        - dataset
      summary: List all Datasets
      responses:
        "200":
          description: the list of Datasets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dataset'
              examples:
                Two:
                  $ref: '#/components/examples/TwoDatasets'
  /organizations/{organization_id}/datasets/search:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
    post:
      parameters:
      - name: page
        in: query
        description: page number to query
        required: false
        schema:
          type: integer
      - name: size
        in: query
        description: amount of result by page
        required: false
        schema:
          type: integer
      operationId: searchDatasets
      tags:
        - dataset
      summary: Search Datasets
      requestBody:
        description: the Dataset search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatasetSearch'
            examples:
              DatasetSearch:
                $ref: '#/components/examples/DatasetSearch'
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              DatasetSearch:
                $ref: '#/components/examples/DatasetSearch'
      responses:
        "200":
          description: the list of Datasets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dataset'
              examples:
                Two:
                  $ref: '#/components/examples/TwoDatasets'
  /organizations/{organization_id}/datasets/copy:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
    post:
      operationId: copyDataset
      tags:
        - dataset
      summary: Copy a Dataset to another Dataset. Source must have a read capable connector and Target a write capable connector.
      requestBody:
        description: the Dataset copy parameters
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatasetCopyParameters'
            examples:
              BreweryDatasetCopyParameters:
                $ref: '#/components/examples/BreweryDatasetCopyParameters'
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              BreweryDatasetCopyParameters:
                $ref: '#/components/examples/BreweryDatasetCopyParameters'
      responses:
        "201":
          description: the Dataset copy operation parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetCopyParameters'
              examples:
                BreweryADT:
                  $ref: '#/components/examples/BreweryDatasetCopyParameters'
        "400":
          description: Bad request
        "404":
          description: the Dataset specified as Source or Target is unknown or you don't have access to it
  /organizations/{organization_id}/datasets/{dataset_id}:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: dataset_id
        in: path
        description: the Dataset identifier
        required: true
        schema:
          type: string
    get:
      operationId: findDatasetById
      tags:
        - dataset
      summary: Get the details of a Dataset
      responses:
        "200":
          description: the Dataset details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
              examples:
                BreweryADT:
                  $ref: '#/components/examples/BreweryADT'
        "404":
          description: the Dataset specified is unknown or you don't have access to it
    patch:
      operationId: updateDataset
      tags:
        - dataset
      summary: Update a dataset
      requestBody:
        description: the new Dataset details.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dataset'
            examples:
              BreweryADTUpdate:
                $ref: '#/components/examples/BreweryADTUpdate'
          application/yaml:
            schema:
              type: string
              format: binary
            examples:
              BreweryADTUpdate:
                $ref: '#/components/examples/BreweryADTUpdate'
      responses:
        "200":
          description: the dataset details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
              examples:
                BreweryADTUpdated:
                  $ref: '#/components/examples/BreweryADTUpdated'
        "400":
          description: Bad request
        "404":
          description: the Dataset specified is unknown or you don't have access to it
    delete:
      operationId: deleteDataset
      tags:
        - dataset
      summary: Delete a dataset
      responses:
        "204":
          description: Request successful
        "404":
          description: the Dataset specified is unknown or you don't have access to it

  /organizations/{organization_id}/datasets/{dataset_id}/compatibility:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
      - name: dataset_id
        in: path
        description: the Dataset identifier
        required: true
        schema:
          type: string
    post:
      operationId: addOrReplaceDatasetCompatibilityElements
      tags:
        - dataset
      summary: Add Dataset Compatibility elements.
      requestBody:
        description: the Dataset Compatibility elements
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/DatasetCompatibility"
              example:
                TwoDatasetCompatibility:
                  summary: 2 Dataset Compatibilities
                  description: 2 Dataset Compatibilities
                  value:
                    - solutionKey: Brewery Solution
                      minimumVersion: "1.0.0"
                    - solutionKey: Brewery Solution
                      minimumVersion: "1.0.1"
      responses:
        "201":
          description: the Dataset Compatibility elements
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DatasetCompatibility'
              examples:
                TwoDatasetCompatibility:
                  summary: 2 Dataset Compatibilities
                  description: 2 Dataset Compatibilities
                  value:
                    - solutionKey: Brewery Solution
                      minimumVersion: "1.0.0"
                    - solutionKey: Brewery Solution
                      minimumVersion: "1.0.1"
        "400":
          description: Bad request
        "404":
          description: the Dataset specified is unknown or you don't have access to it
    delete:
      operationId: removeAllDatasetCompatibilityElements
      tags:
        - dataset
      summary: Remove all Dataset Compatibility elements from the Dataset specified
      responses:
        "204":
          description: the operation succeeded
        "404":
          description: the Dataset specified is unknown or you don't have access to it

  /organizations/{organization_id}/datasets/import:
    parameters:
      - name: organization_id
        in: path
        description: the Organization identifier
        required: true
        schema:
          type: string
    post:
      operationId: importDataset
      tags:
        - dataset
      summary: Import a new Dataset
      requestBody:
        description: the Dataset to import
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dataset'
            examples:
              BreweryADT:
                $ref: '#/components/examples/BreweryADT'
      responses:
        "201":
          description: the dataset details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
              examples:
                BreweryADT:
                  $ref: '#/components/examples/BreweryADT'
        "400":
          description: Bad request
components:
  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: OAuth2 authentication
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          scopes:
            http://dev.api.cosmotech.com/platform: Platform scope
  schemas:
    DatasetSearch:
      type: object
      description: the search options
      properties:
        datasetTags:
          type: array
          description: the dataset tag list to search
          items:
            type: string
      required:
        - datasetTags
    Dataset:
      type: object
      x-class-extra-annotation: "@com.redis.om.spring.annotations.Document"
      description: a Dataset
      properties:
        id:
          x-field-extra-annotation: "@org.springframework.data.annotation.Id"
          type: string
          readOnly: true
          description: the Dataset unique identifier
        name:
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Searchable"
          type: string
          description: the Dataset name
        description:
          type: string
          description: the Dataset description
        ownerId:
          type: string
          readOnly: true
          description: the User id which own this Dataset
        organizationId:
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          type: string
          readOnly: true
          description: the Organization Id related to this Dataset
        tags:
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          type: array
          description: the list of tags
          items:
            type: string
        connector:
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          description: the Connector setup bound to a Dataset
          allOf:
            - $ref: '#/components/schemas/DatasetConnector'
        fragmentsIds:
          type: array
          description: the list of other Datasets ids to compose as fragments
          items:
            type: string
        compatibility:
          type: array
          description: the list of compatible Solutions versions
          items:
            $ref: '#/components/schemas/DatasetCompatibility'
#      required:
#        - name
#        - connector
    DatasetConnector:
      type: object
      description: a Connector setup
      properties:
        id:
          type: string
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          description: the Connector id
        name:
          type: string
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Indexed"
          description: the Connector name
        version:
          type: string
          description: the Connector version
        parametersValues:
          type: object
          additionalProperties:
              type: string
#      required:
#       - id
    DatasetCompatibility:
      type: object
      description: a Dataset compatibility constraint to a Solution version open range
      properties:
        solutionKey:
          type: string
          description: the Solution key which group Solution versions
        minimumVersion:
          type: string
          description: the Solution minimum version compatibility (version included)
        maximumVersion:
          type: string
          description: the Solution maximum version compatibility (version included)
      required:
        - solutionKey
    DatasetCopyParameters:
      type: object
      description: the Dataset Copy Parameters
      properties:
        sourceId:
          type: string
          description: the source Dataset id
        targetId:
          type: string
          description: the target Dataset id
        options:
          type: object
          description: freeform options to path to connectors
          additionalProperties: true
  examples:
    BreweryADT:
      summary: Brewery ADT Dataset
      description: Brewery Dataset in ADT example
      value:
        id: "1"
        name: Brewery ADT reference
        description: Brewery reference model in ADT
        tags:
          - ADT
          - Brewery
          - Reference
        connector:
          id: "1"
          name: ADT Connector
          version: "1.0.0"
          ownerId: "1"
          parametersValues:
            AZURE_TENANT_ID: "12345678"
            AZURE_CLIENT_ID: "12345678"
            AZURE_CLIENT_SECRET: "12345678"
            AZURE_DIGITAL_TWINS_URL: mydt.api.weu.digitaltwins.azure.net
            ADT_QUERY: SELECT * FROM digitaltwins
            EXPORT_CSV_FILE_ABSOLUTE_PATH: /mnt/scenariorun-data
        compatibility:
          - solutionKey: Brewery Solution
            minimumVersion: "1.0.0"
    TwoDatasets:
      summary: Two Datasets example
      description: Two ADT Datasets example
      value:
        - id: "1"
          name: Brewery ADT reference
          description: Brewery reference model in ADT
          tags:
            - ADT
            - Brewery
            - Reference
          connector:
            id: "1"
            name: ADT Connector
            version: "1.0.0"
            ownerId: "1"
            parametersValues:
              AZURE_TENANT_ID: "12345678"
              AZURE_CLIENT_ID: "12345678"
              AZURE_CLIENT_SECRET: "12345678"
              AZURE_DIGITAL_TWINS_URL: mydt.api.weu.digitaltwins.azure.net
              ADT_QUERY: SELECT * FROM digitaltwins
              EXPORT_CSV_FILE_ABSOLUTE_PATH: /mnt/scenariorun-data
          compatibility:
            - solutionKey: Brewery Solution
              minimumVersion: "1.0.0"
        - id: "2"
          name: Brewery ADT future
          description: Brewery future model in ADT
          tags:
            - ADT
            - Brewery
          connector:
            id: "1"
            name: ADT Connector
            version: "1.0.0"
            ownerId: "1"
            parametersValues:
              AZURE_TENANT_ID: "12345678"
              AZURE_CLIENT_ID: "12345678"
              AZURE_CLIENT_SECRET: "12345678"
              AZURE_DIGITAL_TWINS_URL: myotherdt.api.weu.digitaltwins.azure.net
              ADT_QUERY: SELECT * FROM digitaltwins
              EXPORT_CSV_FILE_ABSOLUTE_PATH: /mnt/scenariorun-data
    BreweryADTUpdate:
      summary: Brewery ADT name update example
      description: Brewery ADT reference model name update example
      value:
        name: Brewery ADT new reference
    BreweryADTUpdated:
      summary: Brewery ADT updated Dataset
      description: Brewery Dataset in ADT name updated example
      value:
        id: "1"
        name: Brewery ADT new reference
        description: Brewery reference model in ADT
        tags:
          - ADT
          - Brewery
          - Reference
        connector:
          id: "1"
          name: ADT Connector
          version: "1.0.0"
          ownerId: "1"
          parametersValues:
            AZURE_TENANT_ID: "12345678"
            AZURE_CLIENT_ID: "12345678"
            AZURE_CLIENT_SECRET: "12345678"
            AZURE_DIGITAL_TWINS_URL: mydt.api.weu.digitaltwins.azure.net
            ADT_QUERY: SELECT * FROM digitaltwins
            EXPORT_CSV_FILE_ABSOLUTE_PATH: /mnt/scenariorun-data
        compatibility:
          - solutionKey: Brewery Solution
            minimumVersion: "1.0.0"
    BreweryDatasetCopyParameters:
      summary: Parameters for Dataset copy example
      description: Parameters for Dataset copy from Dataset 1 to 2 example
      value:
        sourceId: "1"
        targetId: "2"
    DatasetSearch:
      summary: Example for dataset search
      description: Parameters to search for a dataset
      value:
        datasetTags:
          - dataset
